CONTRIBUTING.md, README.md
=> PP-1790 Format fixes for open sourcing

src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java
- Order users by username rather than role.
=> PP-1605 Order users by username rather than role.

Jenkinsfile
Adds a Jenkinsfile for `pay-adminusers`.
When this is merged the following jobs need to be disabled + deleted:
Depends on https://github.com/alphagov/pay-chef/pull/163 being merged + deployed.
=> PP-1866 Add Adminusers Jenkinsfile

src/main/java/uk/gov/pay/adminusers/model/SecondFactorToken.java, src/main/java/uk/gov/pay/adminusers/service/UserNotificationService.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
So users get sent “012345” rather than “12345”
=> PP-1901 Pad 2FA codes with leading zeroes if shorter than 6 digits

src/main/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResource.java, src/test/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResourceTest.java
- Created new resource for the legacy way of handle Forgot Password so we can create a new resource for handling the new way (send notifications in adminusers)
=> PP-1977 Prepare adminusers for backward compatibility

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersConfig.java, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/ForgottenPasswordDao.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/infra/GuicedTestEnvironment.java, src/test/resources/config/test-it-config.yaml
Use `FORGOTTEN_PASSWORD_EXPIRY_MINUTES` environment variable (before that it was hard-coded).
=> PP-1977 Use FORGOTTEN_PASSWORD_EXPIRY_MINUTES environment variable

src/main/java/uk/gov/pay/adminusers/model/InviteOtpRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteValidateOtpRequest.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/main/resources/migrations/00021_add_column_expiry_date_invites.sql, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/InviteExpiryTest.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Add invites expiry date. So move logic into the entity.
- Refactored invites otp resources paths.
- Add validation for otp requests.
- Add resource to create user on otp validation.
- Add resource to resend otp
- Return newly created User object on successful invite validation
=> PP-1603 Invite Resource OTP

src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/ValidateOtpAndCreateUserResult.java, src/main/resources/migrations/00022_alter_table_invites_add_column_disabled.sql, src/main/resources/migrations/00023_alter_table_invites_add_column_login_counter.sql, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGetTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Invalidate an invite when:
- creating a user from invite
- the invite is locked
- Add `disabled` and `loginCounter` properties to `InviteEntity`
- Invalidate an `InviteEntity` when creating user from invite
- Add invite locking logic (`disabled` and `loginCounter` properties)
=> PP-1603 Invite invalidation

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/model/UserTest.java, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateAndGetTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Add new Service API object
- Add service name to the response in User API object
with @maxcbc
=> PP-1615 Add service name

src/main/java/uk/gov/pay/adminusers/service/UserServices.java
- Log failed login attempts indicating user 'externalId' and 'loginCounter'
- Log failed OTP attempts indicating user 'externalId' and 'loginCounter'
- Changed some debug levels to info and when user gets locked out to Warn (since is very unlikely to happen).
=> PP-1665 Write log messages on failed login attempts

src/main/resources/migrations/00026_alter_table_invites_remove_constraints.sql
- Removed constrain `NOT NULL` from column `sender_id`
- Removed constrain `NOT NULL` from column `service_id`
with @kakumara
=> PP-2147 Alter table invites to remove constraints

src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/service/AdminUsersExceptionsTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
- removed exception when user is disabled
- altered tests accordingly
=> PP-1979 Change to HTTP200 on disabled user

src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateAndGetTest.java
- removed get user by username method and associated tests
=> PP-1979 removed /v1/api/users?username={username}

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersConfig.java, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/app/config/SecondFactorAuthConfiguration.java, src/main/java/uk/gov/pay/adminusers/service/SecondFactorAuthenticator.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/service/SecondFactorAuthenticatorTest.java, src/test/resources/config/test-it-config.yaml
- `SecondFactorAuthenticator.authorize` now checks against the current 30 time window and the previous one.
- Added tests to prove this.
=> PP-2167 2FA authentication against multiple timewindows

src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java
This was picking up only the first one until one. Now that we support multiple services, removing that logic and making sure tests support multiple service roles.
with @maxcbc
=> PP-1611 enabling user entity to have multiple service roles

src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleUpdater.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java
- updated UserResource's update user permissions to use external id
- updated associated tests and test helpers
with @kakumara
=> PP-1611 Changed update user permissions to use service external id

docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/model/PatchRequest.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/validations/UserPatchValidations.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
=> PP-2430 patch telephone number

src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceFindTest.java
Currently equals to email so this can be considered as a find by email as well too.
=> PP-2359 ability find a user by username

src/main/java/uk/gov/pay/adminusers/service/ServiceRoleUpdater.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java
- Updated the update user service role method to only enforce the minimum-number of admins if the update requested is to downgrade a user from admin to a lower role
=> PP-2456 Fix Admin Min Number check

src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/model/PatchRequest.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/resources/migrations/00031_alter_table_users_add_column_features.sql, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/model/UserTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
This allows user profiles to be patched with features
The features allowed for a user can be viewed on the user profile after the patch
=> PP-2540 Add features to User Profile

src/main/java/uk/gov/pay/adminusers/validations/UserPatchValidations.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchTest.java
* Allow path:'features' and op:'replace' as a valid patch operation for a user
=> PP-2540 Allow Patch Features

src/main/resources/migrations/00032_adjust_paymenttypes_read_permission.sql, src/main/resources/migrations/00033_adjust_emailtemplates_read_permission.sql
These page needs to be shown to all users. (Although certain functions within the pages will still be restricted to higher permissions which is already handled)
=> PP-2584 add payment-types and email-notification-template read permission to all roles

src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/exception/ServiceNotFoundException.java, src/main/java/uk/gov/pay/adminusers/exception/ServiceNotFoundExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/exception/ValidationException.java, src/main/java/uk/gov/pay/adminusers/exception/ValidationExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/model/MerchantDetails.java, src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/model/UpdateMerchantDetailsRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/MerchantDetailsEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ResetPasswordValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/main/resources/migrations/00034_alter_table_services_add_merchant_details_columns.sql, src/main/resources/migrations/00035_add_merchant_details_permission.sql, src/test/java/uk/gov/pay/adminusers/model/UpdateMerchantDetailsRequestTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/RequestValidationsTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceFindTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateMerchantDetailsTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java, src/test/java/uk/gov/pay/adminusers/validations/RequestValidationsTest.java
This PR adds "Merchant details" related changes:
- We added merchant details in `services` table [
6a37cd5]
- We added permissions to `read` and `update` the merchant details [
d5b5366]
- We added a new `PUT /v1/api/services/{serviceExternalId}/merchant-details` endpoint to edit the merchant details [affe4e3]
see commit messages for more information.
with @simad
=> PP-2688 Merchant details related changes

Jenkinsfile
Update Jenkins file to deploy to ECS too and explicitly do not run tests with non ECS deployment
Goes with https://github.com/alphagov/pay-infra/pull/1148
solo @belindacowey
=> PP-3096 ECSify Adminusers in Test

Dockerfile, docker-startup-with-db-migration.sh, docker-startup.sh
Remove docker-startup-with-db-migration and replace with docker-startup with logic
=> PP-3174 Implement database migrations for ECS

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/resources/migrations/00036_alter_table_services_alter_column_name.sql, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java
- Changed service name to be maximum 50 characters
- Modified tests
with @simad
=> PP-3295 Service name length change and validation

Jenkinsfile
- Run e2e, accept and zap in parallel 
- switch each of these on a parameter
=> PP-3436 Run tests in parallel

src/main/resources/migrations/00037_alter_table_services_add_merchant_telephone_number.sql
This PR adds `merchant_telephone_number` database column to `services` table.
=> PP-2897 Add `merchant_telephone_number` database migration

src/main/java/uk/gov/pay/adminusers/model/MerchantDetails.java, src/main/java/uk/gov/pay/adminusers/model/UpdateMerchantDetailsRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/MerchantDetailsEntity.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/model/UpdateMerchantDetailsRequestTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateMerchantDetailsTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Add merchant telephone number property on DAO and API level.
The `telephoneNumber` is optional.
The validation of the format of `telephoneNumber` is done in the client historically.
=> PP-2984 Add merchant telephone number

src/test/java/uk/gov/pay/adminusers/pact/PayInteractionRunner.java, src/test/java/uk/gov/pay/adminusers/pact/PayPactRunner.java, src/test/java/uk/gov/pay/adminusers/pact/UsersApiContractTest.java
Unfortunately we need custom code to publish verification results as there is a
bug in the @PactBroker. See https://github.com/DiUS/pact-jvm/issues/667.
@oswaldquek
=> PP-3616: Publish verification result to Pact Broker

src/test/java/uk/gov/pay/adminusers/pact/PayInteractionRunner.java
=> PP-3616: code cleanup

src/main/resources/migrations/00041_alter_table_services_add_merchant_email.sql
- Added migration script for column `services.merchant_email`
=> PP-3711 Add email address to merchant details

src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/resources/EmailTemplate.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/resources/EmailTemplateTest.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java
Handle PAYMENT_FAILED email template in `/v1/emails/send` endpoint
=> PP-3362 Handle PAYMENT_FAILED email template

src/main/java/uk/gov/pay/adminusers/resources/EmailResource.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java
Better logging when sending emails
=> PP-3362 Better logging when sending emails

Jenkinsfile
=> PP-3707: Tag provider with 'test' on deploy to test environment

Jenkinsfile
A deploy only happens on master branch so adding the conditional is required.
@oswaldquek
=> PP-3707: Tag provider pact on deploy

Jenkinsfile
=> bau: Include contract tests as part of build time

src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/resources/EmailTemplate.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/pact/UsersApiContractTest.java, src/test/java/uk/gov/pay/adminusers/resources/EmailTemplateTest.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java, src/test/resources/config/test-it-config.yaml
- We are introducing on-demand payment collection, with a different email
template from one-off payment. So, we need to introduce a new notify template.
A PR in infra has been raised (https://github.com/alphagov/pay-infra/pull/1670)
=> PP-3678 Add on demand payment collection email template

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersConfig.java, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/app/config/NotifyDirectDebitConfiguration.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/service/NotifyClientProvider.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java, src/test/resources/config/test-it-config.yaml
- Made Direct Debit notify email templates consistent
- Separated Direct Debit configuration
- Fixes
Related PR - https://github.com/alphagov/pay-infra/pull/1671
=> PP-3676 Make Direct Debit notify email templates consistent

src/main/java/uk/gov/pay/adminusers/resources/EmailTemplate.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java
- Added keys for email template to be sent when a mandate is created
=> PP-3676 Send email on mandate created

src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/InviteDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/InviteFinder.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGetTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteFinderTest.java
Adding an endpoint to expose invitations for a service. This will be on the root of the invites resources `/v1/invites` and will accept a query param of `serviceId={externalServiceId}`.
=> PP-3943 List invited users for a service

src/test/java/uk/gov/pay/adminusers/resources/EmailTemplateTest.java
I was asserting on upper case instead of lower case
=> PP-3676 Fix shouldDeserialiseEnumFromLowercaseString test logic

Jenkinsfile
It's already pulled in https://github.com/alphagov/pay-adminusers/blob/e773788a06217816e970217e2e6a814899df73a3/src/test/java/uk/gov/pay/adminusers/infra/PostgresContainer.java#L73.
@oswaldquek
=> bau: do not pull docker image

src/main/resources/migrations/00042_create_table_service_names.sql
- Create a new table `service_names` that will hold the service names in different languages
- Will map to table `services` by service_id and will have a `language` and a `name` columns
=> PP-4096 Created table service_names

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Introduce redirect_to_service_immediately_on_terminal_state flag
- add field redirect_to_service_immediately_on_terminal_state to ServiceEntity
- update/add relevant tests
with @danworth
=> PP-4204 Add redirect flag to service entity

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java
- add json property redirect_to_service_immediately_on_terminal_state to Service class
- update relevant tests
with @sandorarpa
=> PP-4204 Add json property redirect_to_service_immediately_on_terminal_state

docs/api_specification.md
- add API documentation of redirect_to_service_immediately_on_terminal_state
=> PP-4204 Add API documentation

src/main/resources/migrations/00044_alter_table_services_add_column_collect_billing_address.sql
=> PP-4160 Add "collect_billing_address" column to "services" table

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/service/ServiceCreator.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java
- Make DAO read `collect_billing_address` from services table in DB
- Output `"collect_billing_address"` in service response JSON
- Make new services have collect billing address flag set to true
=> PP-4160 Add "collect_billing_address" property to service

src/main/resources/migrations/00045_add_toggle_collect_billing_address_permissions.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java
- Add read permission and add role_permission for all roles
- Add update permission and only add role_permission for 'admin' role
=> PP-4159 Add permissions for toggle billing address

pom.xml
This reverts commit 081fb14f8eaf49e14237df0f2a30fafa60bed70a.
=> Revert "Bump pact-jvm-provider-junit_2.12 from 3.5.24 to 3.6.0"

src/main/resources/migrations/00046_alter_table_services_add_column_current_go_live_stage.sql
- add column current_go_live_stage to services
- set value to 'NOT_STARTED'
with @cobainc0
=> PP-4450 add column current_go_live_stage to services

src/main/java/uk/gov/pay/adminusers/model/GoLiveStage.java, src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- add currentGoliveStage to Entity with default value NOT_STARTED
- add relevant stuff to test helpers
- fix flatMap in ServiceUpdater
with @cobainc0
=> PP-4450 Add current_go_live_stage enumeration type to ServiceEntity

src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java
- add operation validation
- add unit tests for validator
=> PP-4450 Add validation for current_go_live_stage update operation

src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java
Adds updater & test for current_go_live_stage 
with: @cobainc0
=> PP-4450 Adds current_go_live_stage updater to `ServiceUpdater`

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateGoLiveStageTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java
- adds resource test for `current_go_live_stage` get and update endpoints
Tests can be found:
`ServiceResourceUpdateGoLiveStageTest`
`ServiceResourceFindTest`
with: @SandorArpa
=> PP-4450 Add property to service model

src/main/resources/migrations/00047_add_go_live_stage_permission.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java
- new migration adds role permissions for admins only
with: @stephencdaly
=> PP-4449 Add role permissions for Go Live stage

docker-startup.sh
We'll just set these via JAVA_OPTS instead
=> PP-4584: Remove proxy environment variables

src/test/java/uk/gov/pay/adminusers/pact/ProviderContractTest.java
Add needed Pact states for Request To Go Live users used in https://github.com/alphagov/pay-selfservice/pull/1072
=> PP-4449 Add Pact States for Request To Go Live users

src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/model/UserTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
- Added `lastLoggedInAt` property to `UserEntity`
- Added `lastLoggedInAt` property to `User`
=> PP-4594 Add last logged in at property

Jenkinsfile, src/main/java/uk/gov/pay/adminusers/app/healthchecks/MigrateToInitialDbState.java, src/main/java/uk/gov/pay/adminusers/app/util/TrustStoreLoader.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/resources/ResetPasswordValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleUpdater.java, src/main/java/uk/gov/pay/adminusers/service/StripeAgreementService.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/utils/Errors.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/infra/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/adminusers/model/UserTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/DaoTestBase.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateServiceRoleTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
* Remove redundant declarations
* Construct lists more efficiently
* Neater functional constructs
* Better use of Optionals
* Use try-with-resources for managing JDBC Connection objects
* More efficient String handling
=> BAU: More IntelliJ-inspired code cleanups

src/main/resources/migrations/00050_create_table_govuk_pay_agreements.sql
- add script to create table
(new table (govuk_pay_agreements) (columns: service_id (integer -> FK to services.id) NOT NULL, email (varchar 254) NOT NULL, agreement_time (timestamp without time zone) NOT NULL)
=> PP-4581 Add table govuk_pay_agreements

src/main/java/uk/gov/pay/adminusers/model/GovUkPayAgreement.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/GovUkPayAgreementDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/GovUkPayAgreementEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/StripeAgreementEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/GovUkPayAgreementDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/GovUkPayAgreementDaoTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- implement GovUkPayAgreementDao
=> PP-4581 Implement GovUkPayAgreementDao

src/main/java/uk/gov/pay/adminusers/model/GovUkPayAgreement.java, src/main/java/uk/gov/pay/adminusers/resources/GovUkPayAgreementRequestValidator.java, src/test/java/uk/gov/pay/adminusers/resources/GovUkPayAgreementRequestValidatorTest.java
- add GovUkPayAgreementRequestValidator
=> PP-4581 Add request validator

src/main/java/uk/gov/pay/adminusers/app/healthchecks/MigrateToInitialDbState.java, src/main/java/uk/gov/pay/adminusers/resources/ResetPasswordResource.java
lgtm.com spotted a couple of cases where our log messages' placeholders were incorrect. Fix them up so that our logs are what we expect.
=> BAU: Logging fixes - incorrect formatting placeholders

src/main/java/uk/gov/pay/adminusers/persistence/entity/GovUkPayAgreementEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/GovUkPayAgreementDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceGovUkPayAgreementResourceTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceUpdateTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
=> PP-4581 add govuk pay agreement endpoints

docs/api_specification.md
- Remove fields that no longer exist
- Update documentation to include all user fields that do exists
- Remove duplication in docs and reference a single place for the user
object specification
=> PP-4607 Update API documentation for user response

src/main/java/uk/gov/pay/adminusers/app/config/LinksConfig.java, src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
- Add config settings for notify template
- Add method to send email to NotificationService
Sending of the email will be unit tested when the service which invokes the sending of it is added
=> PP-4615 Add configuration for send live email notify template

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java
- Added organisation name validation for maximum characters
- Fixed `ServiceRequestValidatorTest` tests to properly assert on exception
with @DanailMinchev
=> PP-4451 Organisation name validation

src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/exception/ConflictExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/exception/NotFoundException.java, src/main/java/uk/gov/pay/adminusers/exception/NotFoundExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/exception/ServiceNotFoundException.java, src/main/java/uk/gov/pay/adminusers/exception/StripeAgreementExistsException.java, src/main/java/uk/gov/pay/adminusers/model/StripeAgreementRequest.java, src/main/java/uk/gov/pay/adminusers/resources/IpAddressValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/StripeAgreementService.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceSendLiveAccountCreatedEmailTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceStripeAgreementTest.java, src/test/java/uk/gov/pay/adminusers/service/StripeAgreementServiceTest.java
- Success response for POST endpoint is now a 201
- Fixes 500 errors thrown when there are issues with the body of the POST request. Now returns 422 errors with appropriate messages.
- Fixes body of conflict responses to match existing pattern.
=> PP-4539 Fix responses for stripe agreement endpoints

README.md, docs/api_specification.md
- add API specs for the new endpoint
=> PP-4581 add API documentation

src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceGovUkPayAgreementResourceTest.java
- fix endpoint according to the JIRA story
- add another use case (user does not belong to service)
- fix/add relevant tests
=> PP-4581 Fix endpoints

src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java
I'm going to be adding a number of new validations, so just extracting some methods first so it doesn't become a huge mess.
=> PP-4614 Refactor ServiceUpdateOperationValidator

src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java
- Add validation for all possible paths that can be used to update
service merchant details
- Add tests and extract methods in test class to avoid some duplication
=> PP-4614 Add validation for update merchant details patch request

src/main/java/uk/gov/pay/adminusers/model/Link.java, src/main/java/uk/gov/pay/adminusers/model/MerchantDetails.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/MerchantDetailsEntity.java
Rather than hand-rolling our own equals() and hashCode() methods, lean heavily
on helpers from Objects.
Also, make use of String.format() for toString() methods.
=> Use Objects.equals() and .hash() for object ID

src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateMerchantDetailsTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java
- Renamed for consistency with the Service response
- address_line_1 -> address_line1
- address_line_2 -> address_line2
=> PP-4614 Rename fields for merchant details update request

src/test/java/uk/gov/pay/adminusers/pact/ProviderContractTest.java
- remove pact states that were used by selfservice pact tests that
have been removed
- add additional states so more pact tests in selfservice can be
published and verified against adminusers
- made some modifications to existing states to get them working against
selfservice pacts
=> PP-4678 Remove unused pact states and add additional required states

src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/GovUkPayAgreementService.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceGovUkPayAgreementResourceTest.java, src/test/java/uk/gov/pay/adminusers/service/GovUkPayAgreementServiceTest.java
- refactor GovUkPayAgreementService.doCreate to return the model
- update test
=> PP-4453 Refactor create GovUk Agreement to return email and timestamp

src/main/java/uk/gov/pay/adminusers/service/NotificationService.java
- Remove the backward compatibility code which is not needed anymore
=> PP-4759 International telephone number clean up

src/test/java/uk/gov/pay/adminusers/resources/StripeAgreementRequestTest.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Remove a few unused things in the tests which IntelliJ found
=> Intellij fixes

src/main/resources/migrations/00052_add_stripe_bank_details_permissions.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java
=> PP-4462 Add read and update permissions for Stripe bank details

src/main/resources/migrations/00053_add_stripe_responsible_person_permissions.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java
Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>
=> PP-4463 Add read/update permissions for Stripe responsible person

src/main/java/uk/gov/pay/adminusers/model/GoLiveStage.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java
=> PP-4976 Add ENTERED_ORGANISATION_ADDRESS go live stage

Dockerfile, Jenkinsfile, docker-startup.sh, pom.xml
- Upgrade to Java 11
- CI should pass
=> PP-5049 - Migrate to java 11

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
Request from support please see JIRA ticket for details.
Also with some Java 11 magic...`List.of()`.
=> PP-5067 whitelist accessplanit.com

src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java
Add tests to ensure that we can create a service name by only providing `"service_name": {"en": "Service Name"}` without a `"name": "Service Name"` property.
To be clear, this functionality already worked but was not explicitly tested.
This commit adds a little bit of duplication in the tests but this will be removed when we stop supporting `"name": "Service Name"` in create service requests.
=> PP-5061 Tests for creating service with only service_name.en

src/main/resources/migrations/00056_alter_table_services_drop_column_name.sql
=> PP-5061 Drop the name column from the services table

src/main/java/uk/gov/pay/adminusers/service/EmailService.java
=> Use immutable Map.of()s in EmailService

src/main/java/uk/gov/pay/adminusers/exception/ConflictExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteCompleteRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteOtpRequest.java, src/main/java/uk/gov/pay/adminusers/model/ServiceUpdateRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ForgottenPasswordValidator.java, src/main/java/uk/gov/pay/adminusers/resources/HealthCheckResource.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/resources/ResetPasswordResource.java, src/main/java/uk/gov/pay/adminusers/resources/ResetPasswordValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java
Now that we have `Map.of` and friends, we can replace our usage of Guava collections with Java collections.
Is the new code actually nicer?
Does it pass tests (one for CI)
=> Replace Guava collections with Java collections

src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/utils/CountryConverter.java, src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/main/java/uk/gov/pay/adminusers/validations/UserPatchValidations.java
Replace a couple of guava usages with the Java standard library
=> Bit less guava

src/test/java/uk/gov/pay/adminusers/pact/ProviderContractTest.java
=> bau: Reduce pact provider test runs

src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java
Remove an unused import and replace a varargs array of `Pair`s with a `Map`
=> Minor linter cleanups

ruleset.xml
https://pmd.github.io/pmd-6.18.0/pmd_rules_xml_errorprone.html
=> Add PMD XML “Error Prone” rules

pom.xml, src/test/java/uk/gov/pay/adminusers/pact/ContractTestSuite.java
=> PP-5670: Update pay java commons lib

src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/test/java/uk/gov/pay/adminusers/pact/ContractTestSuite.java
- Remove unused import
- Remove try block catching a NullPointerException when processing a
`CreateUserRequest` in favour of safely getting each value from the Json payload.
I ran PMD locally and fixed two of lint errors.
=> BAU Clean up codacy lint errors

pom.xml, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
=> PP-5717: Configure adminusers to use json logging

pom.xml, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/resources/config/config.yaml
=> PP-5776: Configure server request logs to log in json format

pom.xml
- Update maven surefire plugin to 3.0.0-M4
=> PP-4573 Update Maven Plugin

src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResource.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java
Inline path string in the UserResource and ForgottenPasswordResource to
make reading the code easier. This now matches what we do in other
resources.
=> PP-5313 Inline path strings

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java
- whitelist Scottish Natural Heritage for allowed government emails.
=> ZD-3897522 whitelist Scottish Natural Heritage

src/main/java/uk/gov/pay/adminusers/service/NotificationService.java
We aren't getting SMSes when logging in to selfservice on the test-perf-1
environment. Logging the reason.
=> bau: Log NotificationClientException message

.travis.yml, src/test/resources/config/test-it-config.yaml
Adds .travis.yml necessary for running builds on Travis.
Changed log level to ERROR during test runs to make test results legible and prevent filling the build log with request logs.
=> Run builds on travis

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Add accessors for the `experimental_features_enabled` services database column.
* Update Entity 
* Update POJO used for resource response 
* Assert values are correctly set and parsed through to JSON
=> PP-6152 Service entity experimental features flag

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
Requested by Kirsty Armstrong on behalf of `Scottish Social Services
Council and Care Inspectorate`.
=> BAU Add sssc.uk.com to allowed email addresses

src/main/resources/migrations/00059_add_column_sector.sql
- Add's a 'sector' column to the services table for us to begin to store
this information about new and historic services.
=> PP-6257 Add Column Sector

src/main/resources/migrations/00060_add_payouts_permission.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java
- add a new permission, payout:read to permission for all roles
=> PP-6627 add payout read permission

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java
Read new fields from the database and return them in the get service response.
=> PP-6257 Return new service fields in service response

pom.xml, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java, src/test/java/uk/gov/pay/adminusers/utils/telephonenumber/TelephoneNumberUtilityFormatToE164InvalidDataTest.java, src/test/java/uk/gov/pay/adminusers/utils/telephonenumber/TelephoneNumberUtilityFormatToE164ValidUnitedKingdomDataTest.java, src/test/java/uk/gov/pay/adminusers/utils/telephonenumber/TelephoneNumberUtilityIsValidPhoneNumberTest.java
- Uses Junit5 `junit-jupiter-params` library for parameterised unit tests
=> PP-6708 Use Junit5 ParamaterisedTest

src/main/resources/migrations/00063_add_moto_account_masking_permisions.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java
Description:
- Adding permissions for reading and updating MOTO mask input settings
=> PP-7011 Adding MOTO masking permissions

src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetIT.java
We have seen a timeout when trying to get admin emails for all the current live
gateway accounts. Make this more efficient by getting all the emails in one
query.
=> PP-7663: Get admin emails in one query

.gitignore, src/main/resources/migrations/00067_alter_table_services_add_column_current_psp_test_account_stage.sql
- add new column current_psp_test_account_stage to services table
- add default value to above column
- fill existing services with default value
=> PP-7765 add new field to services table

src/main/resources/migrations/00068_add_psp_test_account_stage_permission.sql
- add a new permission and role_permissions for psp test account request
=> PP-7765 add new permission

src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java
- add the new field to the pact service db fixture
=> PP-7765 add current psp test account stage to pact tests

src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCompleter.java
These were detected by running [error
prone](https://github.com/google/error-prone) against this repo.
=> bau: Java fixes detected by error prone

src/main/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleUpdater.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/service/UserServicesFactory.java, src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/main/java/uk/gov/pay/adminusers/utils/telephonenumber/TelephoneNumberUtility.java
These comments were annoying me
=> bau: Remove superfluous comments

src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java
=> bau: Remove xray initialisation

src/main/resources/migrations/00070_create_table_to_test_concourse_db_migration.sql
- Add a real DB migration for adminusers
=> PP-7920 Adminusers DB Migration

src/main/resources/migrations/00071_drop_test_concourse_db_migration.sql
- Drop a real DB migration for adminusers
=> PP-7920 Adminusers Drop DB Migration

src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/test/java/uk/gov/pay/adminusers/resources/InviteUserRequestValidatorTest.java
Remove a deprecated method we’re not using an actually unit-test the method we are using.
=> PP-8728 InviteRequestValidator: remove deprecated method

src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGetIT.java, src/test/java/uk/gov/pay/adminusers/service/InviteFinderTest.java
Add a boolean `password_set` to the invite JSON response, which specifies whether or not a password has been set on the
invitation.
=> PP-8728 Add password_set property to invite JSON response

src/main/resources/migrations/00075_add_stripe_director_permissions.sql
- Add `read` and `update` permissions for Stripe director.
=> PP-8804 Add stripe director permissions

src/main/java/uk/gov/pay/adminusers/app/RestClientFactory.java, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersConfig.java, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/app/config/RestClientConfig.java, src/main/java/uk/gov/pay/adminusers/client/ledger/exception/LedgerException.java, src/main/java/uk/gov/pay/adminusers/client/ledger/model/LedgerTransaction.java, src/main/java/uk/gov/pay/adminusers/client/ledger/service/LedgerService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/client/ledger/service/LedgerServiceTest.java, src/test/resources/config/test-it-config.yaml
Added a ledger service to adminusers and updated the application configuration
Co-authored-by: Sandor Arpa <sandor.arpa@digital.cabinet-office.gov.uk>
=> PP-9279 add ledger client to adminusers

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/Event.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetails.java, src/test/java/uk/gov/pay/adminusers/TestTemplateResourceLoader.java, src/test/java/uk/gov/pay/adminusers/fixtures/EventFixture.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueueTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetailsTest.java, src/test/resources/templates/events/dispute_created_event.json, src/test/resources/templates/sns/dispute_created_sns_message.json
The `event_details` field in an event message is a String containing JSON, rather than nested JSON in the message. Fix deserialisation to expect this.
=> PP-9278 Fix deserialisation of event_details

pom.xml, src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java
- Added gateway_dispute_id to the dispute email notification processed log
- and updated keys for few values
=> PP-9327 Add gateway_dispute_id to log

src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceIT.java
Extra tests to be sure we're not deleting a user.
=> PP-8827: Extra tests

openapi/adminusers_spec.yaml, pom.xml, src/main/java/uk/gov/pay/adminusers/model/ForgottenPassword.java, src/main/java/uk/gov/pay/adminusers/model/Link.java, src/main/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResource.java, src/main/java/uk/gov/pay/adminusers/resources/HealthCheckResource.java, src/main/java/uk/gov/pay/adminusers/resources/ResetPasswordResource.java, src/main/resources/openapi-config.yaml
- Added OpenAPI config ot generate OpenAPI specs
- Added annotations to generate specs for forgotten password, reset password and healthcheck endpoints
- Preview
=> PP-9456 OpenAPI config and specs for few endpoints

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/model/InviteCompleteRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteCompleteResponse.java, src/main/java/uk/gov/pay/adminusers/model/InviteOtpRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteUserRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteValidateOtpRequest.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/resources/openapi-config.yaml
- Added annotations to generate OpenAPI specs for Invite related endpoints
- Update OpenAPI specs
=> PP-9456 OpenAPI specs for Invite related endpoints

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/GovUkPayAgreement.java, src/main/java/uk/gov/pay/adminusers/model/MerchantDetails.java, src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/model/ServiceUpdateRequest.java, src/main/java/uk/gov/pay/adminusers/model/StripeAgreement.java, src/main/java/uk/gov/pay/adminusers/model/StripeAgreementRequest.java, src/main/java/uk/gov/pay/adminusers/model/UpdateMerchantDetailsRequest.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/resources/openapi-config.yaml
- Added annotations to generate OpenAPI specs for services related endpoints
- and updated OpenAPI specs
=> PP-9456 OpenAPI specs for service related endpoints

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/model/PatchRequest.java, src/main/java/uk/gov/pay/adminusers/model/Permission.java, src/main/java/uk/gov/pay/adminusers/model/Role.java, src/main/java/uk/gov/pay/adminusers/model/ServiceRole.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/resources/openapi-config.yaml
- Added annotations to generate OpenAPI specs for users related endpoints
- and updated OpenAPI specs
=> PP-9456 OpenAPI specs for user endpoints

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/resources/ToolboxEndpointResource.java, src/main/resources/openapi-config.yaml
- Updated OpenAPI specs for new endpoint
=> PP-9456 Update OpenAPI specs

.github/workflows/post-merge.yml, src/test/java/uk/gov/pay/adminusers/client/ledger/service/LedgerServiceConsumerTest.java, src/test/resources/pacts/adminusers-ledger-get-payment-transaction.json
- add a new pact test with setup for adminusers as consumer and ledger as provider
=> PP-9307 add new pact test

.github/workflows/post-merge.yml, pom.xml
- update pom.xml with the required pact plugin and dependencies
=> PP-9307 add required pact plugin to pom

.github/workflows/post-merge.yml
=> PP-9307 fix ledger as provider pact test round 2

.github/workflows/run-tests.yml
- cache pacts folder after running tests
=> PP-9307 fix ledger as provider round 3

src/main/resources/migrations/00080_add_stripe_organisation_details_permissions.sql
- Added permissions to view/update organisation details on Stripe connect account.
=> PP-9004 Add permissions for stripe organisation details

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/Event.java, src/main/java/uk/gov/pay/adminusers/queue/model/EventType.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeLostDetails.java, src/test/java/uk/gov/pay/adminusers/TestTemplateResourceLoader.java, src/test/java/uk/gov/pay/adminusers/fixtures/EventFixture.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeLostDetailsTest.java, src/test/resources/templates/events/dispute_lost_event.json
- implement the handling of DISPUTE_LOST event type
=> PP-9576 implement handling of lost dispute event

src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/EventType.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeEvidenceSubmittedDetails.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/TestTemplateResourceLoader.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeEvidenceSubmittedDetailsTest.java, src/test/java/uk/gov/pay/adminusers/service/NotificationServiceTest.java, src/test/resources/config/test-it-config.yaml, src/test/resources/templates/events/dispute_evidence_submitted_event.json
- implement the handling of DISPUTE_EVIDENCE_SUBMITTED event type
=> PP-9576 implement handling of dispute evidence submitted event

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java
- some test account does not have merchant details. Use service name instead
=> PP-9576 fix NullPointerException

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetails.java, src/main/java/uk/gov/pay/adminusers/utils/date/DisputeEvidenceDueByDateUtil.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetailsTest.java, src/test/java/uk/gov/pay/adminusers/utils/date/DisputeEvidenceDueByDateUtilTest.java, src/test/resources/templates/events/dispute_created_event.json
- Updated evidenceDueDate to ZonedDateTime (which is the format that connector sends `evidence_due_date` field)
=> PP-9788 Update evidenceDueDate to ZonedDateTime

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java
- remove personalisation items that are no longer needed.
- update / extend tests
=> PP-9670 refactor sending dispute created email part 2

src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/resources/config/test-it-config.yaml
- Removed feature flags for disputes as email notifications are enabled in all environments.
=> PP-9956 Remove dispute feature flags

src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteRouter.java, src/main/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleter.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleterTest.java
* Don't return Optionals from InviteCompleter
* Don't use WebApplicationException in InviteRouter
* Use structured logging in NewUserExistingServiceInviteCompleter
=> PP-10041: Follow-up from #1639

src/main/java/uk/gov/pay/adminusers/model/InviteType.java
Really this should have been done as part of #1639, but I overlooked it.
=> PP-10041: Make InviteType parsing more robust

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/test/java/uk/gov/pay/adminusers/model/UserEntityTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java
- Refactor to use MockitoExtension
- Remove unnecessary stubbing
- Use Hamcrest assertions
- Fix intellij warnings for JUnit5 tests
=> PP-10051 Refactor user invite tests

src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java
This reverts commit ff0fa08a7cb0e6202526f24a0127651218980d5f.
=> Revert "PP-10041: Start using new InviteType enum values"

.github/workflows/run-tests.yml, README.md
Add a check in the GitHub actions workflow that runs on PR builds to check whether there are uncommitted changes after running `mvn compile`. If there are, this suggests that there have been changes to the API specification and the OpenApi file has not been regenerated. Fail the build when uncommitted changes are detected.
Example of a failed build:
=> PP-10255 Check if there are uncommitted changes to OpenApi file

src/test/java/uk/gov/pay/adminusers/fixtures/InviteEntityFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/RoleEntityFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceEntityFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserEntityFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceFinderTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceSearchTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceUpdateTest.java
Add fixtures for creating InviteEntity, RoleEntity and UserEntity. Rename `ServiceEntityBuilder` -> `ServiceEntityFixture`.
=> PP-10244 Add test fixtures

.secrets.baseline, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/pact/ContractTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateUserIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGenerateOtpIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGetIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceUpdateIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceUserCompleteIT.java
* Rename some methods in InviteDbFixture
* Add new pact test states to set up invites
=> PP-10083: Add pact tests

src/main/resources/migrations/00082_alter_services_add_column_takes_payments_over_phone.sql
- a new page is being added to the onboarding flow, asking service if it takes MOTO payments
- this first step is to add takes_payments_over_phone column to services table in adminusers db
=> PP-10199 Add column takes_payments_over_phone

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/InviteServiceRequest.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateServiceIT.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java
Removed fields:
* password
* telephone_number
These are not sent by the new registration journey.
=> PP-10063: Remove fields from `/v1/api/invites/service` request body

pom.xml
Reverts alphagov/pay-adminusers#1889
=> Revert "build(deps): bump dropwizard.version from 2.1.4 to 2.1.5"

pom.xml
Reverts alphagov/pay-adminusers#1974
=> Revert "build(deps): bump dropwizard.version from 2.1.4 to 2.1.6"

pom.xml
=> BAU bump `dropwizard` 2.1.4 -> 2.1.6

pom.xml, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersConfig.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
Set up a prometheus metric endpoint /metrics.
Append ECS metadata info (via the PrometheusDefaultLabelSampleBuilder class in pay-java-commons) as default labels.
Analogus to https://github.com/alphagov/pay-connector/pull/4625, which has been tested.
=> PP-11223: Set up prometheus metrics

.secrets.baseline, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/pact/ContractTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ForgottenPasswordDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java, src/test/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateInviteToJoinServiceIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateSelfRegistrationInviteIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceUserCompleteIT.java, src/test/java/uk/gov/pay/adminusers/resources/ResetPasswordResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ToolboxEndpointResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateServiceRoleIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceFindIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetMultipleIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorProvisioningIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Removed remaining uses of username from endpoints and replaced it to return email
=> PP-11283 Remove remaining usernames from adminusers

src/test/java/uk/gov/pay/adminusers/pact/ContractTest.java
We have removed username from adminusers DB and associated classes. We need to refactor selfservice contract tests to use email instead of username.
- refactor ContractTest
=> PP-11283 refactor contract tests

src/main/resources/migrations/00086_alter_table_users_drop_username.sql
- Dropped ``username`` column from ``users`` table
=> PP-11283 Drop username column

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/User.java, src/test/java/uk/gov/pay/adminusers/pact/ContractTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ToolboxEndpointResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateServiceRoleIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceFindIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetMultipleIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorProvisioningIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleIT.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
We have removed username from the users table. We are removing it from the User class as well.
- remove username from User class
- update code accordingly
- update tests accordingly
- update openapi accordingly
=> PP-11327 remove username from User

src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java
- update the findUser validator
=> PP-11327 update findUser validation

src/test/java/uk/gov/pay/adminusers/infra/SqsTestDocker.java
=> BAU: Pin to elasticmq v1.4.2

pom.xml
=> Bump commons libs

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java
- update swagger example to properly represent the changes we made.
=> PP-11327 update openapi spec

pom.xml
Reverts alphagov/pay-adminusers#2129
=> Revert "build(deps): bump pay-java-commons.version from 1.0.20230810083009 to 1.0.20230825122025"

pom.xml
- update eclipselink to latest
=> P-11652 update eclipselink

.github/dependabot.yml
Also format the file so that `yamllint` likes it (in a separate commit).
=> PP-11652 Fix Dependabot config for ignoring Dropwizard 4

.github/dependabot.yml
Some indentation went wrong in commit 9b968ae78b98254e5efdf816a3c9098066804787.
=> BAU — Fix Dependabot YAML file

src/main/java/uk/gov/pay/adminusers/client/ledger/model/LedgerSearchTransactionsResponse.java, src/main/java/uk/gov/pay/adminusers/client/ledger/model/LedgerTransaction.java, src/main/java/uk/gov/pay/adminusers/client/ledger/service/LedgerService.java, src/test/java/uk/gov/pay/adminusers/client/ledger/service/LedgerServiceTest.java
- Added service method to search transactions for a gateway account.
- This will be used to find the last transaction for the service and archive service if no payments have been taken in the last 7 years
=> PP-11205 Add method to search Ledger transactions

src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDao.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDaoIT.java
- Removes users from service when service is archived.
=> PP-11205 Detach users from service

src/test/java/uk/gov/pay/adminusers/client/ledger/service/LedgerServiceConsumerTest.java, src/test/resources/pacts/adminusers-ledger-search-transactions.json
- Added pact test for new interaction - ledger transaction search
=> PP-11205 Add pact test

src/main/resources/migrations/00087_alter_services_add_column_archived_date.sql
- Added new column `archived_date` which will be set when services are archived.
=> PP-11205 Add archived_date column to services

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/resource/ExpungeAndArchiveHistoricalDataResourceIT.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceEntityFixture.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java
- Sets `archived_date` when a service is archived
- Returns the field in the API.
=> PP-11205 Set archived_date

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java
Make the regex into a constant so we don’t compile it every time.
=> PP-11355 make search service regex static final

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java
Allow both ' and ’
- update regex to allow real apostrophe.
=> PP-11355 add real apostrophe to regex

src/test/java/uk/gov/pay/adminusers/pact/ConnectorQueueMessageContractTest.java
Add a messaging pact test on the provider side.
=> PP-11279: Connector-adminusers messaging pact test

src/test/java/uk/gov/pay/adminusers/pact/ProviderContractTestSuite.java
As there is no connector consumer pact yet (to come in a later PR) this can be run with no side effects now.
=> PP-11279: Run connector queue message contract test

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/run-tests.yml, src/test/java/uk/gov/pay/adminusers/infra/AppWithPostgresAndSqsRule.java, src/test/java/uk/gov/pay/adminusers/infra/AppWithPostgresExtension.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/DaoTestBase.java
Bump Postgres container to 15.2, like we run in real environments.
=> PP-11895-upgrade-postgres-container

src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java
- For any ledger errors (performance related or any other), logs a warning and continues archiving services
=> PP-11855 Log and continue archiving services for Ledger errors

src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDao.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDaoIT.java
=> PP-11812 Remove unused DAO method

.github/dependabot.yml
org.eclipse.persistence.jpa 3.x and above only works with Jakarta EE and not Java EE
=> BAU ignore org.eclipse.persistence.jpa

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
Added hissib.or.uk to the allowed email list
=> PP-12798 Add hssib to allowed email  list

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/main/java/uk/gov/pay/adminusers/service/SecondFactorAuthenticator.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/SecondFactorAuthenticatorTest.java
=> PP-12791 Replace Clock with InstantSource

src/main/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResource.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java
Remove unnecessary logging of user input for Invite and Forgotten Password API operations
=> PP-12766 remove unnecessary logging of user input

.secrets.baseline, README.md, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
Bind to 127.0.0.1 by default instead of 0.0.0.0
I followed the exact same testing strategy as https://github.com/alphagov/pay-connector/pull/5539 and achieved the same results
=> PP-13145: Accept BIND_HOST env var and default to localhost

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/RoleName.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceIT.java
Add a `role` query parameter to `GET /v1/api/services/{serviceExternalId}/users` so users with specific roles can be returned.
=> PP-13030: Return users by role

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/AssignServiceAndRoleRequest.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleCreator.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAssignServiceAndRoleToUserIT.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleCreatorTest.java
This commit implements these improvements:
- Use Java class representation of a POST body instead of JsonNode
- Use provided dropwizard and hibernate validation rather than custom validation
=> PP-13030: Refactor method that assigns service and role to user

src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/validations/UserPatchValidations.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- update `PATCH /v1/api/users/{userExternalId}` to allow for adding/removing features more robustly, using `add`/`remove` patch operations
=> PP-13546 Update patch User to allow for adding/removing features

pom.xml
Fine tune Dropwizard 4 bom dependencies.
=> PP-13651 refine Dropwizard 4 migration
