pom.xml, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/resources/pacts/selfservice-authenticate-adminusers.json, src/test/resources/pacts/selfservice-create-forgotten-password-adminusers.json, src/test/resources/pacts/selfservice-create-user-adminusers.json, src/test/resources/pacts/selfservice-get-forgotten-password-adminusers.json, src/test/resources/pacts/selfservice-get-user-adminusers.json, src/test/resources/pacts/selfservice-login-attempts-adminusers.json, src/test/resources/pacts/selfservice-session-adminusers.json, src/test/resources/pacts/selfservice-update-password-adminusers.json
- State data for create user when username already exists (unhappy scenario).
- Create a base user as username 'existing-user' for idempotent API operations.
- Add state for forgotten password scenarios as Consumer expects (fixed codes).
- Add state for login attempt scenario (max reached).
=> PP-1718 Pack Provider tests (User Api)

pom.xml
Notify client 2.2.1 seem to be doing something different in the HTTP requests with regards to SSL certs validation. While in production it seems all fine, SSL handshake against our custom certificates that we use with pay-stubs seems to failing with following exception. So downgrading to the same version (2.2.0) used by connector (which seem to be working and possibly more relaxed). We probably should investigate this in more detail later.
```
adminusers_1         | [2017-03-17 08:19:43.489] [2fa-sms-0] ERROR c.g.s.n.NotificationClient - javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
adminusers_1         | …
```
=> PP-1716 downgrade notify client version

src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
The way selfservice checks for user is disabled or not at first factor and second factor are slightly different. 
On first factor (username/password) it checks disability before authenticating username/password. On Second factor we check after 2fa verification. 
So, in order to have the same locking effect to user we need to adjust the 2fa locking set only after max_attempts exceeded.
=> PP-1716 adjust 2fa login counter check

README.md, docs/api_specification.md, pom.xml, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/model/Role.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleUpdater.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/service/UserServicesFactory.java, src/test/java/uk/gov/pay/adminusers/fixtures/RoleDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Introduced `PUT  /v1/api/users/{username}/services/{service-id}`
Instead of adding business logic on to the existing UserService (which is already grown bit too much), have introduced a guice assisted factory pattern to obtain business service components that can be used by UserResource. The upside of this guice factory is that we can have @Transactional around the component method as usual.
And we can unit test each individual business service object separately without messing around other business services (unlike UserServicesTest.java)
=> PP-1819 update user service role

src/main/resources/migrations/00016_alter_table_users_unique_email.sql, src/main/resources/migrations/00017_alter_table_users_unique_username.sql, src/main/resources/migrations/00018_alter_table_users_drop_column_is_new.sql, src/main/resources/migrations/00019_add_constraint_service_gateway_accounts_gateway_account_id.sql, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateAndGetTest.java
-  unique email / username.
-  unique gateway accounts in service_gateway_accounts.
- Drop temporary column 'is_new'
=> PP-1771 Clean up after users migration (add constraints)

src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java
- We have an issue in forgotten passwords not resetting passwords when email does not match db case so making the find case insensitive for both username (is this what is being used) and email.
=> PP-1896 Username and email case insensitive on findBy DAO methods

src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java
- Use LOWER function in both sides of the queries rather than use Java and PG ones. Inconsistency on this (mixin Java / PG)  can cause issues difficult to find if the character set is treated somehow differently.
=> PP-1896 Use LOWER function in both sides

Jenkinsfile
Calls the `deploy` Jenkinsfile library function with `tagAfterDeployment` set to `true`, which means that the `TAG_AFTER_DEPLOYMENT` parameter passed to the invoked Jenkins job is also set to true
with @mrlumbu
=> PP-1866 Call deploy function with TAG_AFTER_DEPLOYMENT set to true

Jenkinsfile
Changes the Jenkinsfile to call the library function `dockerTag` after running tests. This is necessary because the `buildApp` function called earlier no longer does Docker tagging (it was doing it too early and getting it wrong in any case).
=> PP-1866 Call dockerTag function after test stage

src/main/java/uk/gov/pay/adminusers/app/util/RandomIdGenerator.java, src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/model/CreateUserRequestTest.java, src/test/java/uk/gov/pay/adminusers/model/UserEntityTest.java, src/test/java/uk/gov/pay/adminusers/model/UserTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
- Removed random exteranlId generation from JsonNode: we must ignore JsonNode externalIds (coming from clients) when creating User object
- Generate externalIds using Java
=> PP-1717 Genarate externalId only when needed

src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateAndGetTest.java
Add `/v1/api/users?username=email@example.com` filter endpoint which will be used in `selfsevice` for `Login` and `Forgot your password?` functionality.
=> PP-1717 Add username filter endpoint

pom.xml, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/service/NotifyClientProvider.java, src/main/java/uk/gov/pay/adminusers/service/UserNotificationService.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
- We are running an old version of Notify client, this upgrade will allow us to send emails in _adminusers_ therefore we can implement Forgotten Password and Invite email notifications.
=> PP-1857 Upgrade Notify client to version 3.1.1-RELEASE

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleUpdater.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/fixtures/RoleDbFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateAndGetTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleTest.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java, src/test/resources/pacts/selfservice-authenticate-adminusers.json, src/test/resources/pacts/selfservice-create-user-adminusers.json, src/test/resources/pacts/selfservice-get-user-adminusers.json, src/test/resources/pacts/selfservice-session-adminusers.json
Modifies pay-adminusers service to use only `external id` in api endpoints.
Before that we were querying for `username` and `externalId` in api endpoints.
This PR replaces `username` with `externalId` from the endpoints and services (removes the `username` condition)
- Modified `UserResource` and removed `is_new_api_request ` GET parameter
- Modified service and dao layers and removed the `username` condition
- Modified tests and documentation
=> PP-1717 username in api urls cleanup

src/main/java/uk/gov/pay/adminusers/model/InviteOtpRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java
- OTP generation requires telephone number and password to be sent along with the code of the invite (in url).
- Async send sms code. So a new resource for resending must be provided in next PR.
- InviteService has way too many collaborators, so the refactoring will be done in the last PR for PP-1603.
=> PP-1603 Generate OTP for Invites

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResource.java, src/main/java/uk/gov/pay/adminusers/service/ForgottenPasswordServices.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResourceTest.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java, src/test/resources/pacts/selfservice-create-forgotten-password-adminusers.json
- Added notifications as part of forgotten password journey. Since we don't need any information to send back to selfservice (was building the link for the notification in that side), removed response payload, returning a 200 OK response when creating a Forgotten Password successfully (consistent with second factor)
- These changes assume selfservice is using v2 of the resource. This PR will make possible then to use this new version (next PR). So this PR depends on https://github.com/alphagov/pay-selfservice/pull/332 to be merged and deployed.
=> PP-1977 Forgotten Password notifications

src/main/java/uk/gov/pay/adminusers/model/ForgottenPassword.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ForgottenPasswordEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/ForgottenPasswordDbFixture.java, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ForgottenPasswordDaoTest.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java
Add `userExternalId` to `ForgottenPassword` API object.
When we get `ForgottenPassword` by code, self service will need `userExternalId` property
=> PP-1977 Add userExternalId to ForgottenPassword

src/main/java/uk/gov/pay/adminusers/service/ForgottenPasswordServices.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java
- (Minor) Use email user field rather than username for sending notifications.
=> PP-1977 Use email of user for notifications

src/main/java/uk/gov/pay/adminusers/model/ForgottenPassword.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ForgottenPasswordEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResource.java, src/main/java/uk/gov/pay/adminusers/service/ForgottenPasswordServices.java, src/test/java/uk/gov/pay/adminusers/fixtures/ForgottenPasswordDbFixture.java, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ForgottenPasswordDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResourceTest.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/resources/pacts/selfservice-create-forgotten-password-adminusers.json, src/test/resources/pacts/selfservice-get-forgotten-password-adminusers.json
- Revert back to `/v1/api/forgotten-passwords` endpoint, which uses the new `externalId` logic.
- Remove `username` from `ForgottenPassword`, because we don't need it anymore.
=> PP-1977 Forgotten password clean up

pom.xml
Add the test scope attribute to the pact reference
To prevent false positives in security scans for items that are not deployed.
=> PP-2084 Update pom to make pact a test dependency

pom.xml
`commons-beanutils:commons-beanutils:jar:1.8.0` brought in as a transient test dependency has the following vulnerability:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0114
- https://snyk.io/vuln/SNYK-JAVA-COMMONSBEANUTILS-30077
Pinned down version of the dependency to `1.9.3` and marked explicitly as test scoped.
=> PP-2114 Upgraded commons-beanutils dependency which contains vulnerability

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
EmailValidator initial implementation
- Implemented isPublicSectorEmail() method which checks if the email belongs to UK public sector domain.
- Generic email validation is not implemented here (it is implemented in Self Service).
with @maxcbc
=> PP-1615 EmailValidator initial implementation

src/main/resources/migrations/00024_alter_table_invites_add_column_type.sql, src/main/resources/migrations/00025_alter_table_services_add_column_external_id.sql
column type to invites table -> in order to support user and service invites
column external_id to services table. In order to not expose primary keys to public.
with @maxcbc
=> PP-2147 add new columns to support self creation of services

pom.xml, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/app/config/LinksConfig.java, src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/model/InviteRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteServiceRequest.java, src/main/java/uk/gov/pay/adminusers/model/InviteType.java, src/main/java/uk/gov/pay/adminusers/model/InviteUserRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/InviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/InviteServiceFactory.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateServiceTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGetTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteUserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/resources/config/test-it-config.yaml
- Introduced `InviteServiceFactory`
- Created a abstract `InviteRequest` class, with child classes for user and service invite requests.
- Added generic email validator to `EmailValidator` to validate email inputs.
- Extracted the links config as a injectable object as it could be injected in services instead of the whole configuration object.
- Feedback link in the email template currently directs to the `support` page in our product page (frontend). We may need to change this in future.
TODO:
There are couple of edge cases which we still need to discuss with @stephenmc.
=> PP-2147 create service invite resource

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/model/ServiceUpdateRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/ServiceServicesFactory.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java
Currently supported operation are 
- to update service name (`op`=`replace` and `path`=`name`)
- to update assign new gateway account ids (`op`=`add` and `path`=`gateway_account_ids`)
Updated tests case and readme
=> PP-2147 Update service attribute resource

docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/service/InviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/service/InviteCreatorTest.java, src/test/resources/config/test-it-config.yaml
As per discussion with Tim macavoy and Stephen M., adding extra notifications during unhappy paths.
1. self service creation, user exists and disabled scenario.
2. if a valid invite exits during self service creation, resend the invite.
with @maxcbc
=> PP-2147 Fix service invite email couple of scenarios

src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDao.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/ServiceCreator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceServicesFactory.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUserRemover.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUserRemoverTest.java
- Added resource (_DELETE_) to remove a user from a service `/v1/api/services/{serviceExternalId}/users/{userExternalId}`
- It requires a payload containing the external Id of the user performing the removal. Ie:
`{
"remover_id": "fahjd7237ebjhdadasd"
}`
- Returns a `200 OK` when removing an user from a service succeeded
- Returns a `400 BAD REQUEST` when payload is malformed or remover is missing
- A users cannot remove themselves. Returns `409 Conflict` when user to be removed  is same as the remover
- User performing the removal must be Admin (`403 Forbidden` otherwise)
- If the userExternalId does not belong to the given service, returns`404 Not Found`.
- Remover does not belong to the same service or is not an Admin of the given service or does not exist it returns a `403 Forbidden`
=> PP-1608 Remove user from a Service.

src/main/resources/migrations/00027_add_delete_users_permission.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateAndGetTest.java
- Create permission `users-service:delete` permission.
- Add this permission to `admin` and `super-admin` roles.
- Many operations in adminusers relies on Roles rather than permissions (for Admin operations), this needs to be changed to rely only on permissions when `super-admin` role gets used.
=> PP-1608 Add user service delete permission

src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateServiceTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Since users can be removed from all their services all the resources should not rely on users belonging to services.
- Services returns as empty for user not belonging to a service therefore happens the same with its permissions / role.
=> PP-1608 Allow empty services for an user

src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java
We have an otp/validate endpoint. However, this also creates a user.
When we have a service invite otp to validate, we do not want to create a user.
This commit adds a new endpoint otp/validate/service which just does the otp
validation with no side effects. Ideally we will move over to using this for user
invites as well, with a secondary request to create user.
=> Pp 1615 self create service 1

src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUserRemover.java, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java, src/test/resources/pacts/selfservice-delete-user-adminusers.json
- Add new Header `GovUkPay-User-Context`. This represents the user performing the operation. At the moment only for one resource (_Delete user_) but eventually will be in a filter mapping URL's with specific permissions. Pending discussion.
- Add delete user API pact tests using new approach using `GovUkPay-User-Context` Header.
=> PP 1608 Delete user API - Introducing GovUkPay-User-Context

src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java
Adding support for external ID based service extraction for list of users.
Leaving service Id based resource for backward compatibility. (Until selfservice is migrated) 
Need to remove later.
=> PP-2147 Get list of users for a service by external ID

src/test/java/uk/gov/pay/adminusers/infra/PostgresContainer.java
- Change postgres local image logging from `syslog` to`json-file` so logs can be retrieved.
=> PP-2271 Use json-file as docker login rather than syslog for postgres

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java
Given that this is already mapped and loaded in ServiceEntity, it makes sense to include these id's as part of the service domain model.
We can consider removing this dependency if we consider introducing a orchestration to a different layer at some point.
=> PP-1611 including gateway account id's in to the service

src/main/java/uk/gov/pay/adminusers/model/ServiceRole.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceRoleEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/model/UserTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateAndGetTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
Introducing concept of role per service. 
This means a user can have different roles per service. Deprecating top level `Service` and `Role` to leave support for backward compatibility. Need to remove them once selfservice is migrated to consume `service_roles`.
with @maxcbc
=> PP-1611 User to posses knowledge of ServiceRole

src/main/java/uk/gov/pay/adminusers/app/healthchecks/DatabaseHealthCheck.java
Registers some metrics and then pulls in the new data for the metrics whenever
the healthcheck is called.
As the pay-connector work does.
=> PP-2032: Add database metrics to pay-adminusers

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleCreator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceRoleUpdater.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/service/UserServicesFactory.java, src/test/java/uk/gov/pay/adminusers/model/UserEntityTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateServiceRoleTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUserRemoverTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
Added a new resource that adds a new service role to a user. This is required in order to write a proper accept test for this story.
- It makes sure the same service is not added to the user twice.
- Also renamed the `notFoundService` exception as it was confusing (throwing 404).
with @maxcbc
=> PP-1611 add service to user

src/main/java/uk/gov/pay/adminusers/model/Link.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/InviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteServiceFactory.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCompleteTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
In order to cleanly use invites to create entities (Users, Services),
it makes sense to have an action on the Invite resource that triggers the
transformation of the Invite into the required resources.
This commit adds an endpoint of form `/v1/api/invites/{inviteCode}/complete`
which finds the specified invite, and creates user and service (if needed) based on
data in the invite. It then disables the invite.
=> PP-1615 Add complete invite resource

pom.xml
notifications-java-client 3.1.2-RELEASE is affected by
https://snyk.io/vuln/SNYK-JAVA-ORGBITBUCKETBC-30206?utm_campaign=vuln_alert&utm_medium=email&utm_source=Vuln
This upgrades to 3.1.3-RELEASE, which fixes the vulnerability
=> PP-2330 Upgrade notify client

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateUserTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java
Handling the corner case in case of the inviting user is already a member of the service. 
Using HTTP 412 (pre-condition failed) error code, just because we need a separate error code, as we have exhausted all other sensible http codes already in this resource.
Also updated the Readme for `complete` resource.
=> PP-1876 invite existing user (already exists)

src/main/java/uk/gov/pay/adminusers/model/InviteOtpRequest.java, src/main/java/uk/gov/pay/adminusers/model/OtpGenerateRequest.java, src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/InviteOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/InviteRouter.java, src/main/java/uk/gov/pay/adminusers/service/InviteServiceFactory.java, src/main/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/UserOtpDispatcher.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGenerateOtpTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteUserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteRouterTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserOtpDispatcherTest.java
This now generates + dispatches otp for both USER and SERVICE invites.
Using the same routing approach similar to `complete` resource
Leaving the old `generateOtp` resource for backward compatibility
=> PP-1615 refactored otp generate resource to support service invites

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/model/InviteOtpRequest.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGenerateOtpTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpTest.java
- Removed deprecated `/v1/api/invites/otp/generate` endpoint. It is not used by selfservice anymore.
We use the new `/v1/api/invites/{code}/otp/generate` instead.
- Added documentation
=> PP-1615 remove deprecated otp generate endpoint

src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
In notify email templates currently https://www.payments.service.gov.uk/support.html is returning `404 - not found`. That is why https://www.payments.service.gov.uk/contact/ seems to be more appropriate.
=> PP-1615 Correct supportUrl

src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java
This was caused by reusing the same logic between generateOtp when a new user signs up (where password is mandatory) by resend otp step(in self provisioning a service and new user creation).
As we have refactored out the generate Otp to new resource `v1/api/invites/{code}/otp/generate` this resource is only used by resend attempts. So no need of password setting in with either cases.
It probably better to remove this method (InviteService.reGenerateOtp()) altogether and use a an approach similar to UserOtpDispatcher.java to avoid confusion.
=> PP-2382 fix otp resend causing password reset to blank

pom.xml
Same as for connector:
This was pulled by a transitive dependency of liquibase, although they themselves doesn't need it
=> PP-2017 remove jstl dependency

docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/model/ServiceUpdateRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/CustomBrandingConverter.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/main/resources/migrations/00029_drop_column_custom_branding.sql, src/main/resources/migrations/00030_add_column_custom_branding_json.sql, src/test/java/uk/gov/pay/adminusers/model/ServiceUpdateRequestTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateCustomBrandingTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Updated Database column type to `json`. 
Added validation to verify if provided value is a JSON.
Currently validations do not restrict the structure of the JSON as long as its a Json, leaving it flexible for expansion later. The clients (technically) can store any JSON. Although, for now we will be implementing the `Frontend` only to store/retrieve `css_path` and `image_path`.
=> PP-2453 Made custom_branding to be a JSON object

pom.xml
Bumped up version of `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` from `2.8.7`
to `2.8.10` to address the vulnerabilities below:
- Arbitrary Code Execution
  Vulnerable module: commons-collections:commons-collections
  Introduced through: commons-validator:commons-validator@1.6
- Deserialization of Untrusted Data
  Vulnerable module: com.fasterxml.jackson.core:jackson-databind
  Introduced through: black.door:hate@v1r4t0 and com.fasterxml.jackson.datatype:jackson-datatype-jsr310@2.8.7
See https://snyk.io/org/govuk-pay/project/3156ff8a-edc9-48a0-b735-604974f35e83
=> PP-2636 Address Deserialization of Untrusted Data vulnerability (CVE-2017-7525)

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetMultipleTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
- added `/v1/api/users/?ids={externalId1},{externalId2}...`
- Also split out `create` and `get` user resource tests
This enables us to do mass look ups on users when we get a group of user externalIds. i.e. in a list of transaction events
=> PP-2575 Added get multiple users endpoint

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
We currently hard code the list of whitelisted domains allowed for account set up. This commit adds acas.org.uk to allow selfservice account creation.
We should move this to DB and have an API to modify some day.
Today is not that day.
=> PP-2694 Add acas.org.uk to email whitelist 

pom.xml, src/test/java/uk/gov/pay/adminusers/infra/PostgresContainer.java, src/test/java/uk/gov/pay/adminusers/infra/PostgresDockerRule.java
- Current integration tests are using a non ideal manually built Postgres image for testing. Even less ideal is pulling the image locally when it does not exist (example as in new machines, docker images clean up, changed a reference to a new image)
- Pull explicitly the docker image before running the tests
- Upgrade docker-client (test scope) version from 8.1.1 -> 8.9.2
=> PP-2959 Explicit docker pull postgres image for testing

Dockerfile, chamber.sha256sum, docker-startup.sh
To get this to run in ECS we require the docker container to be able to
start up the app with chamber to get the variables from the environment.
This commit adds a new codepath to run the app with chamber if the
`CHAMBER` env var is set, and it adds a chamber binary (copied from
pay-selfservice).
solo @tlwr
=> PP-3096: Add chamber to docker startup script

Dockerfile, docker-startup.sh, run-with-chamber.sh
I broke this yesterday, this fixes the broken change and adds a new
script which just calls the regular script but with chamber.
We override the entrypoint in the ECS task definition to call the regular startup script with chamber.
solo @tlwr
=> pp-3096: fix chamber startup startup

src/main/java/uk/gov/pay/adminusers/logger/RequestIdLoggingHandler.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
- Adminusers is using a different pattern (a request Id logging filter, instead of
specifying the log format in `config.yaml`, so the format in that file is slightly different
- Removed colors
=> PP-3129 Adapt adminusers' log formats to match the other microservices

Dockerfile, docker-startup-with-db-migration.sh
Like pay-connector there should be 2 docker startup scripts:
- docker-startup.sh
- docker-startup-with-db-migration.sh
This is so ECS will not run the migrations.
=> PP-3096: Refactor docker-startup WRT migrations

Dockerfile, chamber.sha256sum, run-with-chamber.sh
As a stop gap we need to use dominic's version of chamber as this can take the
cert path as an environment variable.
So I've just taken the chamber from selfservice and have switched to using it.
=> bau: Use doms chamber

Dockerfile, run-with-chamber.sh
chamber is now in the base image for java and node
we don't vendor it anymore
and it is in /usr/bin so it is in the path
solo @tlwr
=> BAU: Use chamber in base image

src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceFindTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java
The id was being built into the url instead of the external id.
Updated test with link assertions and removed the deprecated logic using numeric service ids.
Refactored endpoints and method parameters to reflect more explicitly which id is being used.
@belindac  @danailminchev
=> PP-3063 Self links for service resource in adminusers is wrong

src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/utils/Comparators.java, src/test/java/uk/gov/pay/adminusers/utils/ComparatorsTest.java
We are introducing external account ids which are alphanumeric. In order to maintain backwards
compatibility with numeric internal ids we can't use the Numeric Comparator any more.
This PR introduces a new comparator that sorts the numeric account ids before the alphanumeric ids
=> PP-3061 Sort Gateway Accounts with ad-hoc comparator

src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java
- `gatewayAccountIds` in a service can now be non-numeric, as we are migrating microservices to using external ids instead of internal ids.
- There's no point in validating the create service request anymore, as the only cause for a `BAD REQUEST` was supplying non  numeric ids.
=> PP-3061 Gateway account ids might be not numeric

Jenkinsfile
It should only tag after an ECS deploy
solo @tlwr
=> BAU: Adminusers shouldn't tag after a regular deploy

pom.xml
- upgrade Dropwizard to latest due to security vulnerability of current version
- pin jackson-version to 2.9.4 (deserialization vulnerability)
- remove jersey2 dependencies
- temporary use of mockito 2.0.54-beta (upgrade to latest requires code changes)
- upgrade guava to latest
=> PP-3332 Upgrade Dropwizard to 1.2.2

src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/service/UserCreator.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java
Remove the deprecated `service_ids` property from create user request which is not used anymore.
Related PR: https://github.com/alphagov/pay-infra/pull/1385
=> PP-2897 Remove the deprecated `service_ids` property

docs/api_specification.md, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/pact/UsersApiTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ForgottenPasswordDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ForgottenPasswordResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateServiceTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateUserTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceUserCompleteTest.java, src/test/java/uk/gov/pay/adminusers/resources/ResetPasswordResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateServiceRoleTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceFindTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetMultipleTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleTest.java
- To generate `username`s and `email`s we were using `org.apache.commons.lang3.RandomStringUtils` which generated random, but sometimes not unique values.
- Also, we were sharing `UserDbFixture` with the same initial values
This PR fixes the errors like:
```
16:19:42 ERROR:  duplicate key value violates unique constraint "users_username_key"
16:19:42 DETAIL:  Key (username)=(ipjSodwJAl) already exists.
16:19:42 STATEMENT:  INSERT INTO users ("createdAt", disabled, email, external_id, features, login_counter, otp_key, password, session_version, telephone_number, "updatedAt", username, version) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
16:19:42 ERROR:  current transaction is aborted, commands ignored until end of transaction block
16:19:42 STATEMENT:  SELECT 1
``` …
=> PP-3551 Unique constraint users username key failure fix

docs/arch/adr-001-merchant-details-and-sending-emails.md 
Outcome of a discussion we had on Tuesday 27th March 2018 triggered by our need to send the merchant’s telephone number in Direct Debit emails.
=> ADR for merchant details and sending emails

src/main/resources/migrations/00038_add_column_second_factor_to_users.sql, src/main/resources/migrations/00039_add_column_provisional_otp_key_to_users.sql, src/main/resources/migrations/00040_add_column_provisional_otp_key_created_at_to_users.sql
* `second_factor` (defaults to `sms`)
* `provisional_otp_key` (will be used as a holding area to store a new OTP key while the user is setting it up)
* `provisional_otp_key_created_at` (will be used for a timestamp for when the new OTP key was created so we can expire it if the user does not complete the setup)
=> PP-3576 Add new columns to support logging in with 2FA apps

src/main/java/uk/gov/pay/adminusers/model/SecondFactorMethod.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/SecondFactorMethodConverter.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UTCDateTimeConverter.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/model/UserEntityTest.java, src/test/java/uk/gov/pay/adminusers/model/UserTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/SecondFactorMethodConverterTest.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceRoleUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Add properties for second factor, provisional OTP key and provisional OTP key created at timestamp, to match the new database columns in the users table.
When creating a new user, default the second factor to be SMS and have the other two properties be null.
=> PP-3576 Add new 2FA properties to user

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/SecondFactorAuthenticator.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorProvisioningTest.java, src/test/java/uk/gov/pay/adminusers/service/SecondFactorAuthenticatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
Add endpoint to add a provisional Base32 OTP key to a user. This will be part one of the process for configuring a user to use a 2FA authenticator app instead of text message codes for signing in. Part two will confirm the user has set up the app correctly and will permanently change the key.
Currently, when we need to generate an OTP key (i.e. what’s stored alongside each user in the database), we use one of the methods in `RandomIdGenerator` (we’re not consistent: we use different methods for direct new user creation versus invitations) to get a string.
However, the GoogleAuth library we use requires input secrets to be Base32-encoded. To meet this requirement, we currently (unconditionally) convert the string by taking its UTF-8 bytes and then Base32-encoding them. This somewhat …
=> PP-3576 Add endpoint for creating provisional OTP key

README.md, docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorProvisioningTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
• Activate previously provisioned OTP key (provisioned by endpoint added in PR #177)
• Ability to specify second factor method (SMS or app)
=> PP-3576 Add endpoint for activating provisional OTP key

src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/test/java/uk/gov/pay/adminusers/resources/RequestValidationsTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceSecondFactorAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Make it so that a call to `/v1/api/users/{externalId}/second-factor` with a body of `{"provisional": true}` causes the provisional OTP key to be used when generating the security code sent via text message (error if there isn’t a provisional OTP key).
Requests without a body continue to use the regular OTP key as before.
=> PP-3576 Add ability to send 2FA SMS with security code from provisional OTP key

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
- Whitelisting all '@nhm.ac.uk' addresses to pass the email validation.
=> PP-3635 Whitelist National History Museum on account creation

Dockerfile
When chamber moved into the base image, we didn't fully clean up. Remove this
stray code which adds and then removes openssl.
=> PP-3666 Remove no-op from dockerfile

src/main/java/uk/gov/pay/adminusers/app/healthchecks/Ping.java, src/test/java/uk/gov/pay/adminusers/app/healthchecks/PingTest.java
- Equals operation unreliable since there is a time component involved. Running these tests multiple times eventually fails due to timestamp comparison in the healthcheck:
Ping: `<Result{isHealthy=true, timestamp=2018-04-18T12:05:02.688+0100}>`
Expected: `<Result{isHealthy=true, timestamp=2018-04-18T12:05:02.687+0100}>`
- Modified the test to check only for _isHealthy_ result
=> PP-3657 Fix flaky tests. PingTest

src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
- UserServicesTest.shouldReturn2FAToken_whenCreate2FA_evenIfNotifyThrowsAnError. Verify the promise is completed exceptionally when it completes rather than immediately.
=> PP-3657 Fix flaky test. UserServicesTest.shouldReturn2FAToken_whenCreate2FA_evenIfNotifyThrowsAnError

Jenkinsfile
When doing the selenium tests for staging we decided adminusers should
only run DD smoke tests. Updating the Jenkinsfile so that there is
consistency across all the environments
solo @belindac
=> PP-3602 Change card payments to DD smoke tests

docs/arch/adr-001-merchant-details-and-sending-emails.md
All feedback was in favour of the ADR, which also had broad support in the meeting that spawned it.
=> Change status of ADR 001 from “Proposed” to “Accepted”

Jenkinsfile
Reinstated e2e config removed
Changed smoke test to DD, products should only run after products and products-ui
solo @belindac
=> PP-3602 Revert incorrectly removed e2e config and change smoke tests to DD

README.md, pom.xml
- Prepare maven project for running contract testing on isolation.
- `mvn clean install` excludes contract tests
- Add new 'contract-tests' profile activated by the existence of a 'runContractTests'
environment variable so `mvn clean install -DrunContractTests` would run the contract
tests only. This will fit our requirements for running contract tests in pipeline with
a single command.
=> PP-3615 Contract testing maven profile

src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/model/PaymentType.java, src/main/java/uk/gov/pay/adminusers/resources/EmailRequest.java, src/main/java/uk/gov/pay/adminusers/resources/EmailRequestParser.java, src/main/java/uk/gov/pay/adminusers/resources/EmailResource.java, src/main/java/uk/gov/pay/adminusers/resources/EmailTemplate.java, src/main/java/uk/gov/pay/adminusers/resources/InvalidEmailRequestException.java, src/main/java/uk/gov/pay/adminusers/resources/InvalidEmailRequestExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/resources/InvalidMerchantDetailsException.java, src/main/java/uk/gov/pay/adminusers/resources/InvalidMerchantDetailsExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/service/NotifyClientProvider.java, src/main/java/uk/gov/pay/adminusers/service/StaticEmailContent.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/EmailRequestParserTest.java, src/test/java/uk/gov/pay/adminusers/resources/EmailResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/EmailTemplateTest.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java, src/test/resources/config/test-it-config.yaml
- Adminusers is now in charge of sending emails on behalf of direct debit connector.
This PR adds and endpoint so that direct debit connector can send adminusers details about
the email that needs to be sent.
- Non direct debit specific information (like service name or merchant details) are already
stored in Adminusers, so we need to "merge" the two personalisations to send emails.
- Adding direct debit notify configurations (template ids and a different api keys)
=> PP-3669 Add endpoint for sending direct debit emails

src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java
If we cannot send an email due to merchant details not being configured, log the gateway account ID
=> PP-3669 Log gateway account ID if empty merchant details error

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceFindTest.java
- We were assuming that gateway account ids are numeric. This has changed
since introducing Direct Debit. We need to allow searching by external
gateway account id, so this PR removes the validation rules which requires
ids to be numeric.
=> PP-3712 Allow alphabetic gateway account ids when finding services

Jenkinsfile
Verify the pact just before deploy. Have chosen to do this in the Deploy stage  as we already have too many stages. `checkPactCompatibility` is provider/consumer agnostic so we just in the service name, commit sha and environment to it.
See https://build.ci.pymnt.uk/job/pay-adminusers/view/change-requests/job/PR-205/1/console and search for `"deployable":true,"reason":"All verification results are published and successful"` for a working demonstration.
=> Pp 3629 verify provider deployment

src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java
- General renaming and sanity check of variables. Turns out adminusers will always send service name and merchant details along with the email, so this simplifies things quite a bit.
=> PP-3713 Update direct debit email personalisation

src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java
This endpoint gets all the services.
IMO It should be implemented as:
```
/services
```
but instead it has to be implemented as:
```
/services/list
```
(we should never have a service id which is `list`)
This is because the current `/services` endpoint is a find endpoint that
returns a single service (when you pass in `gatewayAccountId` as a query
param)
I feel like the path I chose is the lesser of two evils.
solo @tlwr
=> BAU: Add services/list endpoint

pom.xml
Upgrading so pact verification don't get published by default. See
https://github.com/DiUS/pact-jvm/issues/695. This is to prevent development
machines from accidentally publishing verifications to the pact broker.
@oswaldquek
=> PP-3842: Upgrade pact jvm provider

pom.xml
This upgrades Jackson from 2.9.1 to 2.9.6 and Jetty from 9.4.7.v20170914 to
9.4.10.v20180503
=> PP-3934: Upgrade Dropwizard to 1.2.7

pom.xml
This upgrades Jetty from 9.4.10 to 9.4.11
=> PP-3937: Upgrade Dropwizard from 1.2.7 to 1.2.8

src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetMultipleTest.java
- We can now have duplicated external ids in the list, so returning not found is not a great ideas as it will always return not found if the same user has issued multiple refunds
=> PP-3959 Do not return not found when an empty body suffices

pom.xml, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/app/filters/XRayHttpClientFilter.java, src/main/java/uk/gov/pay/adminusers/app/util/XRaySessionProfiler.java, src/main/resources/sampling-rules.json
Adds incoming request tracing/segmenting. This allows the flowing of traces from upstream services (self-service) into connector, which can then be visualised using the aws console, or called via the API.
Outbound http requests to any downstream services is a WIP and was previously failing build/test, so we are splitting the work up in order to get the quick win/advantages above.
=> PP-2495 AWS x-ray on application

src/test/java/uk/gov/pay/adminusers/pact/UsersApiContractTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Because we need to run the contract tests multiple times (using pacts tagged
with 'master', 'test', 'staging' and 'production') we need to refresh the
database by deleting data, otherwise provider states like "a user exists with
the given external id 7d19aff33f8948deb97ed16b2912dcd3" (see
UsersApiContractTest.java) would fail on the next re-run.
@oswaldquek
=> PP-4082: Refresh database

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceUpdateTest.java, src/test/resources/fixtures/resource/service/patch/update-name-only-single-object.json
When the update service attribute endpoint was changed to also accept an array of objects rather than just a single object, the `ServiceRequestValidator.validateUpdateAttributeRequest` method was modified to figure out if it was passed an array and validate every element in the array if so. This made the `ServiceRequestValidator` more complex. This commit simplifies things somewhat by doing the following (this is a conceptual description of a series of changes; the final result melds them all in to one):
- Change `ServiceRequestValidator.validateUpdateAttributeRequest` so it no longer tries to handle an array and assumes it just has a single object
- Move `ServiceRequestValidator.validateUpdateAttributeRequest` and its dependent private methods out in to its own …
=> PP-4096 Refactor service update attribute request validation

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/model/ServiceUpdateRequestTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceUpdateTest.java, src/test/resources/fixtures/resource/service/patch/update-cy-name-only.json, src/test/resources/fixtures/resource/service/patch/update-en-and-cy-name-only.json, src/test/resources/fixtures/resource/service/patch/update-name-and-update-cy-name.json, src/test/resources/fixtures/resource/service/patch/update-name-service-name-different-values.json
For updating the multilingual service name, we used to expect requests like this:
```json
[
{
"op": "replace",
"path": "service_name",
"value": {
"en": "Rectify your renal records"
}
}
]
```
Now we expect requests like this:
```json
[
{
"op": "replace",
"path": "service_name/en",
"value": "Rectify your renal records"
}
]
```
In addition to being more in line with [JSON Patch](http://jsonpatch.com/) (but note we are still not strictly compliant), this also makes it easier to change multiple language variants of the service name at once in a natural fashion:
```json
[
{
"op": "replace",
"path": "service_name/en",
"value": "Rectify your renal records"
},
{
"op": "replace",
"path": "service_name/cy",
"value": "Addaswch eich cofnodion arennol"
}
]
```
Furthermore, it makes it simple to reuse …
=> PP-4096 Change the API for multilingual service name updates

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/model/ServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java
The `Service` object contains a `serviceNames` map, which basically only exists to get returned as JSON like this:
```json
"service_names": {
"en": "English Service Name",
"cy": "Welsh Service Name"
}
```
Change the way the `serviceNames` map is constructed so that a multilingual name is not included if the name is either the empty string or all whitespace, as if the name were not set for that language.
This makes it easier for upstream consumers of the JSON to determine that there is no meaningful service name for a particular language and fall back to something sensible (such as using the English name, which will almost always be set).
In addition, remove `Service.setServiceNameMap(Map)` method and instead allow multilingual service names to be specified when constructing the object via …
=> PP-4096 Do not return empty or blank multilingual service names

docs/api_specification.md
Update adminusers internal API docs to reflect that we now return and support setting translated variants of the service name.
=> PP-4096 Update docs now we have multilingual service names

src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ResetPasswordValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/test/java/uk/gov/pay/adminusers/resources/RequestValidationsTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceUpdateTest.java, src/test/resources/fixtures/resource/service/patch/array-replace-service-name-cy-blank.json
When receiving a request to replace one of a service’s multilingual service names, allow empty or all-whitespace strings because — in combination with the feature that means we won’t ever return a
blank service name when someone retrieves a service — this is the best way we have for users to remove a multilingual service name right now.
However, don’t allow an English service name (JSON path `service_name/en`) to be blank because that is mandatory.
with @danworth
=> PP-4096 Allow blank multilingual service names when updating

src/test/java/uk/gov/pay/adminusers/pact/UsersApiContractTest.java
Taking out the PACT_CONSUMER_TAG before meant that the pay-adminusers provider
tests running in the consumer (e.g. pay-selfservice) PR builds wasn't using the
consumer pact tagged with its branch name.
@oswaldquek
=> bau: Reinstate PACT_CONSUMER_TAG

src/main/resources/migrations/00043_add_redirect_to_service_immedidately_flag.sql
- add `redirect_to_service_immediately_on_terminal_state` boolean to `services`
table.
- add default value of `false`.
- update existing entries to default value of `false`.
=> PP-4204 add redirect to service immediately on terminal state flag

src/main/java/uk/gov/pay/adminusers/model/ServiceUpdateRequest.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceUpdateTest.java, src/test/resources/fixtures/resource/service/patch/replace_redirect_immediately_invalid_value.json, src/test/resources/fixtures/resource/service/patch/replace_redirect_immediately_to_true.json
- add validation for service Patch operation to replace `redirect_to_service_immediately_on_terminal_state`.
- add operation to replace value.
- updated unit and resource tests.
with @sandorarpa
=> PP-4204 Add redirect to service immediately flag to service PATCH operation

src/test/java/uk/gov/pay/adminusers/infra/PostgresContainer.java
- We use `govukpay/postgres:9.6.6` in other microservices and should be consistent
=> BAU Upgrade PostgreSQL Docker image to newer one

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/service/ServiceCreator.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java
Set "collect billing address" and "redirect to service immediately on terminal state" flags correctly
- "collect billing address" and "redirect to service immediately on terminal state" flags were not set when used in `uk.gov.pay.adminusers.service.ServiceInviteCompleter.complete` consequently they were initialised to `false`
- make sure we initialise them in central place like `uk.gov.pay.adminusers.persistence.entity.ServiceEntity.from` and initialise `ServiceEntity` with default values as in database
- added missing tests
=> PP-4160 Set "collect billing address" and "redirect to service immediately on terminal state" flags correctly

pom.xml, src/test/java/uk/gov/pay/adminusers/infra/PostgresContainer.java, src/test/java/uk/gov/pay/adminusers/infra/PostgresDockerRule.java
- Mirror change made in pay-connector to remove the need for the
DOCKER_HOST and DOCKER_CERT_PATH which were not required.
- Upgrade version of jackson-jaxrs-base dependency (2.5.4 -> 2.9.6)
which was causing tests to fail.
- Upgrade version of jackson-datatype-guava (2.88 -> 2.9.6) and 
jackson-jaxrs-json-provider (2.88 -> 2.9.6) which were not causing
failures but were also an older version
Related pay-connector changes:
https://github.com/alphagov/pay-connector/commit/1f5ad7b6ec1dd8ae27b3c9dd3a7fd98556264693
=> PP-4159 Get tests running locally with docker for mac

src/test/java/uk/gov/pay/adminusers/pact/ProviderContractTest.java
- change the hard coded service id in the contract test to match that of already defined in selfservice.
Due to the nature of pact test version in selfservice we can't use dynamic params for contract tests.
with @stephencdaly
=> PP-4159 Change service id in pact test

src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- fix failing tests by truncating 'services' table at the end of each
tests
with @stephencdaly
=> BAU: fix DatabaseTestHelper

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
The [Care Inspectorate](http://www.careinspectorate.com/) regulates social work and social care services in Scotland.
In addition, put the public sector email domain names in alphabetical order and add a subdomain test for acas.org.uk email addresses.
It may be easier to review this by going through the three commits one by one.
=> PP-4426 Add careinspectorate.com to public sector email account whitelist

pom.xml
This turns
`[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!`
into
`[INFO] Using 'UTF-8' encoding to copy filtered resources.`
=> BAU: Configure maven for UTF-8 encoded source

pom.xml
Since 0ecff2068702092ff1820a81fce1e3ff9ebe30ea we don't use this library
directly, instead we use it via pay-java-commons. Remove the unnecessary
dependency.
=> BAU: Remove Spotify docker-client

src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java
##WHAT
- fix validation for ServiceUpdateOperationValidator that it checks whether the value for 'name' and 'service_name/xx' is string
=> PP-4521 Updating name with a non string value should not return 500

src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateNameTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java
- refactor ServiceUpdater to automagically update English language service name when updating the 'name' field
=> PP-4520 Updating a service's name should also update English language service name as well

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
Allow new domain socialworkengland.org.uk ( see Zendesk #3544527)
=> PP-4575 Allow domain socialworkengland.org.uk

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
Sort the domain names in ascending order
- Rename `PUBLIC_SECTOR_EMAIL_DOMAIN_REGEX_PATTERNS` to `PUBLIC_SECTOR_EMAIL_DOMAIN_REGEX_PATTERNS_IN_ASCENDING_ORDER` to explicitly document the order of domain names
- Sort domain names by ascending order
Related PR: https://github.com/alphagov/pay-adminusers/pull/326
=> PP-4575 Fix email validator domain name ordering

src/main/resources/migrations/00048_create_table_stripe_agreements.sql
- Create `stripe_agreements` table to hold `ip_address`, `service_id` and
`agreement_time`.
- Discussed the option of defaulting the `agreement_time` to `NOW()` to provide
the option of letting postgres set the value however this would be inconsistent
with existing implementations so it was discouraged.
- `service_id` is unique since there can be only one stripe agreement per service.
=> PP-4539 Create stripe_agreements table to hold IP address.

src/main/java/uk/gov/pay/adminusers/persistence/dao/StripeAgreementDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/StripeAgreementEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/StripeAgreementDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/StripeAgreementDaoTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Add `StripeAgreementDao` to manage persistence of stripe agreements.
- Add `StripeAgreementEntity`.
- Add tests for `StripeAgreementDao` including necessary fixtures and methods to
`DatabaseTestHelper` class.
=> PP-4539 Create components to persist stripe agreement information

pom.xml, src/test/java/uk/gov/pay/adminusers/pact/ProviderContractTest.java
Deprecate our custom PayPactRunner, and upgrade the pact library to version
3.6.1.
This commit is in conjunction with alphagov/pay-jenkins-library@2ca9dc2.
@oswaldquek
=> bau: fix pact publishing issue

src/main/resources/migrations/00049_alter_table_users_add_column_last_logged_in_at.sql
- The `last_logged_in_at` column will be used to log when the user last logged in
=> PP-4594 Add "last_logged_in_at" column to "users" table

src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
- Making the log lines look more like connector's by adding additional info as to what is reported. 
This helps in two way: searches are going to return  more uniform results, and we will have less noise when looking for errors. For example,`level=error` will help isolating the `logger.error` lines rather than lower  level ones which simply have the word error in the message
=> PP-4602 - change structure of adminusers loglines

src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCompleter.java
We have some code like this (simplified):
```java
return inviteDao.findByCode(inviteCode).map(inviteEntity -> {
// Do some stuff to create an InviteCompleteResponse
return Optional.of(response);
}).orElseGet(Optional::empty);
```
This is silly. The `Optional.map(…)` method wraps what’s returned in an `Optional`, so when `Optional<InviteCompleteResponse>` is returned, it becomes `Optional<Optional<InviteCompleteResponse>>` . Then `.orElseGet(Optional::empty)` unwraps the outer `Optional` so we just have `Optional<InviteCompleteResponse>`, which is returned.
We can avoid this muppetry by changing the code to be like this:
```java
return inviteDao.findByCode(inviteCode).map(inviteEntity -> {
// Do some stuff to create an InviteCompleteResponse
return response;
});
```
(If for some reason we …
=> BAU: Stop needlessly wrapping Optionals in Optionals

src/main/java/uk/gov/pay/adminusers/model/StripeAgreement.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/StripeAgreementDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/StripeAgreementEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/StripeAgreementService.java, src/test/java/uk/gov/pay/adminusers/fixtures/StripeAgreementDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/StripeAgreementDaoTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceStripeAgreementTest.java, src/test/java/uk/gov/pay/adminusers/service/StripeAgreementServiceTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Previously was searching by service ID which required first looking
up the service in a separate query
- Refactored code to move more logic into the service from the resource
=> PP-4539 Make StripeAgreementDao search by service external id

src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/exception/ConflictException.java, src/main/java/uk/gov/pay/adminusers/exception/ConflictExceptionMapper.java, src/main/java/uk/gov/pay/adminusers/exception/GovUkPayAgreementNotSignedException.java, src/main/java/uk/gov/pay/adminusers/service/SendLiveAccountCreatedEmailService.java, src/test/java/uk/gov/pay/adminusers/service/SendLiveAccountCreatedEmailServiceTest.java
- Add service to send email with tests
- Add GovUkPayAgreementNotSignedException which extends ConflictException which DropWizard will map to a CONFLICT error response. This follows how we throw and map exceptions in direct-debit-connector and avoids throwing WebApplicationExceptions from the service layer.
=> PP-4615 Add service to send live account created email

src/main/java/uk/gov/pay/adminusers/model/CreateUserRequest.java, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/resources/GovUkPayAgreementRequestValidator.java, src/main/java/uk/gov/pay/adminusers/utils/Errors.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/DaoTestBase.java
Tidy some things IntelliJ didn't like
- Use try-with-resources to avoid a possible JDBC `Connection` leak
- Make some things package-private
- Turn a field into a local variable
- Remove unused methods
- Remove redundant initialisers
- Make `GovUkPayAgreementRequestValidator` more functional
=> Intellij tidyups for DaoTestBase

src/test/java/uk/gov/pay/adminusers/utils/telephonenumber/TelephoneNumberUtilityIsValidPhoneNumberTest.java
- Add more testing for telephone numbers with special characters, related to whitelisted NAXSI rules:
```
1007 - "str:--"
1010 - "str:("
1011 - "str:)"
1016 - "str:#"
1206 - "str:/"
1302 - "str:<"
1303 - "str:>"
1310 - "str:["
1311 - "str:]"
```
Related PR: https://github.com/alphagov/pay-infra/pull/1993
=> PP-4759 Add more testing for telephone numbers with special characters

src/main/java/uk/gov/pay/adminusers/service/NotificationService.java
- When calling Notify client and `sendSms(...)` method use `E164` format in case we receive random formats
=> PP-4759 Always use one telephone number format with Notify client

pom.xml, src/main/java/uk/gov/pay/adminusers/resources/HealthCheckResource.java, src/test/java/uk/gov/pay/adminusers/resources/HealthCheckResourceTest.java
Apply the same change made in pay-direct-debit-connector to adminusers'
healthcheck resource, making it simpler and with a more functional style.
Bring the unit test over from pay-publicapi
=> Be more functional in HealthCheckResource

Dockerfile
Upgrade to our OpenJDK base image based on Alpine 3.9 with OpenJDK 8u201
=> PP-4895: Upgrade Alpine & Java

src/main/resources/migrations/00054_add_stripe_vat_number_company_number_permissions.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateTest.java
- Add `stripe-vat-number-company-number:update` and `stripe-vat-number-company-number:read` permissions which will be used in "VAT number and company number" workflow
=> PP-4949 Add Stripe vat number company number permissions

ruleset.xml
Only one rule (`AvoidThrowingRawExceptionTypes`) for now so we can check if it works.
If it does, the rules in this file will override the default ones Codacy uses (i.e. it will give us fewer warnings). We can add more rules later, probably using the default Codacy rules as a starting point.
This file is intended for use with PMD 5.8.1 even though it’s legacy because that’s what Codacy has enabled by default. We may choose to move to PMD 6.0.0 as we get more comfortable with the tool.
=> Add PMD 5.8.1 ruleset configuration for use with Codacy

src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/UserCreator.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java
Two separate commits:
- When creating a service using the `ServiceInviteCompleter`, set the English service name as well as the default service name.
- When creating a service via the `UserCreator` with a user with a list of gateway account IDs, set the English service name as well as the default service name.
=> PP-5061 Always set English service name when creating service

src/main/resources/migrations/00055_backfill_english_service_names.sql
Database migration to insert a row with the English-language service name into the `service_names` table if there is not already one present for the service.
This should ensure that every English-language service name is duplicated in the `service_names` table.
This won’t lock the table so it’s possible that other service name changes made while this is running may result in inconsistencies and there’s a tiny chance a service trying to update their service
name while this is running may encounter an error. However, the chances are very small (service names are not changed very often) and we can easily check for inconsistencies afterwards and fix any
that are found (which at the very worst may just mean old service names continue to be used for longer than anticipated).
=> PP-5061 Migration SQL to backfill English-language service names

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/UserCreator.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Stop using `ServiceEntity.getName()` in favour of `ServiceEntity.getServiceNames().get(SupportedLanguage.ENGLISH).getName()`, which should return the same thing now that all services have an `'en'` entry in the `'service_names'` table (and updating the name on the service updates in both tables).
`ServiceEntity.getName()` is now only used in tests.
=> PP-5061 Don’t use ServiceEntity.getName() in production code

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/service/ServiceCreator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCompleter.java
When creating a `ServiceEntity` from a `Service` with `ServiceEntity.from(Service)`, use `ServiceEntity.addOrUpdateServiceName(ServiceNameEntity)` to add all the service names provided by `Service.getServiceNames()`.
Two pieces of code create `ServiceEntity`s with `ServiceEntity.from(Service)`: `ServiceCreator` and
`ServiceInviteCompleter`. Both use Service objects they’ve just created and which only have English-language service names. Both `ServiceCreator` and `ServiceInviteCompleter` used to call `ServiceEntity.addOrUpdateServiceName(ServiceNameEntity)` to add their English service names to the `ServiceEntity`. These two calls have been removed and `ServiceEntity.from(Service)` now does the job itself by calling `ServiceEntity.addOrUpdateServiceName(ServiceNameEntity)` with every
name …
=> PP-5061 Copy across names when creating ServiceEntity from Service

src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityTest.java
Make `ServiceEntityBuilder`, which is only used by tests, always add a `ServiceNameEntity` containing the English service name to built `ServiceEntity`s to better reflect how `ServiceEntity`s exist in reality (they are either loaded from the database and always have an English `ServiceNameEntity` or will newly-created and have had an English `ServiceNameEntity` set).
Update tests that relied on the old behaviour.
=> PP-5061 Make ServiceEntityBuilder always add 'en' ServiceNameEntity

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityTest.java
When updating the English-language service name, stop updating the legacy service name i.e. `name` on `ServiceEntity`, which maps to the `name` column in the `services` table in the database.
This is safe to do because nothing ever reads from the name property of `ServiceEntity` for non-test purpose any more.
This may lead to the name column in the `services` table in the database becoming out of sync with the `service_names` table but nothing relies on the former and we intend to remove it soon.
=> PP-5061 Stop updating the legacy service name

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Don’t write legacy service name (represented by the `name` property on the `ServiceEntity`, which maps to the `name` column in the `services` table in the database) when creating a new service.
Since this was the last thing that set the name property on the `ServiceEntity` (and no non-test code ever read it), remove the property and its getters and setters. Fix the tests that relied on this property (most of these should have been updated when we stopped writing the legacy service name when updating the service name in commit 54fd08789f7dab7ea776727c4d96ddfe887ff244 — in retrospect, perhaps this commit and that one should have been done in one go).
=> PP-5061 Don’t write legacy service name when creating service

docs/api_specification.md, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/ServiceCreator.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java
When processing a request to create a new service, ignore the `"name"` property and only use the names from the `"service_name"` property.
Only selfservice creates services and it no longer sends the `"name"` property (but it does always include `"service_name"` with at least an `"en"` property).
Since this involves changes to the `ServiceResource` and `ServiceCreator`, make them not use an `Optional<List<String>>` for the gateway account IDs because optionals of lists are cursed.
=> PP-5061 Ignore "name" property of service creation requests

src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Stop integration tests from inserting the legacy service name into the database when creating a service for a test. Nothing ever reads this column (relying on the appropriate row in the `service_names` table instead).
=> PP-5061 Stop integration tests inserting legacy service name

docker-startup.sh
Bash has a more concise way to do environment variable default values. Use it.
=> Small cleanup to docker-startup.sh

src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java
When deserialising a JSON payload for creating a service, don’t only look specifically for English and Welsh service names. Instead, iterate over the values of the `SupportedLanguage` enum
and look for service names in those languages.
This further centralises the `SupportedLanguage` enum as the single source of truth for what languages we support and will make adding support for more languages in the future require fewer code changes.
=> Create service: don’t hard-code recognised service name languages

src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java
I realised there’s an even simpler way to do this
=> Simplify service name extraction code when creating service

src/main/resources/migrations/00057_add_link_gocardless_account_permission.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java
A permission didn't exist for connecting a direct debit account to a go cardless account in selfservice
=> PP-5139 Add connected go-cardless account permission

README.md, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
There's no need to have separate environment variables for every single
selfservice URL as there's nowhere in Pay's codebase that makes use of
this functionality. It would also help with overriding the base
selfservice URL for end-to-end tests and we could remove some extra
environment variables from our Terraform code.
Removed `SELFSERVICE_*_URL` environment variables from the app's
YAML config and README.
Functionality should be unaffected, so make sure everything works as
usual.
=> REP-137: Remove redundant environment variables

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/service/EmailService.java, src/main/java/uk/gov/pay/adminusers/service/ForgottenPasswordServices.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/service/SendLiveAccountCreatedEmailService.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/UserOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/infra/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/SendLiveAccountCreatedEmailServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
The `NotificationService` was returning things as `CompletableFuture` in
some hopes of making the calls to Notify's API asynchronous. However the
status of the calls was never checked and it looks like adminusers
doesn't reallu care whether the API call was successful or not and
carries on regardless. 
I've not changed this behaviour but instead
explicitly catch the `Exception`s thrown by `NotificationService` and
avoided the mess introduced by `CompletableFuture`.
Error logging behaviour should be the same.
- Run unit and integration tests and check the build is successful
=> REP: Stop misusing asynchronous calls to Notify

ruleset.xml
Initially, use the PMD Java “Best Practices” rules (documented at https://pmd.github.io/pmd-6.18.0/pmd_rules_java_bestpractices.html) but exclude certain rules we don’t want to have applied with comments where appropriate.
With these rules, PMD finds roughly 50 problems with adminusers, which I intend to fix shortly.
=> Update PMD rule set to use PMD 6.x rules rather than legacy rules

pom.xml, src/test/java/uk/gov/pay/adminusers/pact/ContractTest.java, src/test/java/uk/gov/pay/adminusers/pact/ContractTestSuite.java, src/test/java/uk/gov/pay/adminusers/pact/ProductsUIContractTest.java, src/test/java/uk/gov/pay/adminusers/pact/SelfServiceContractTest.java
Currently when a consumer build is kicked off, the provider contract test will
run in its entirety. For example, in a selfservice build, the adminusers provider
contract tests will run as well. However, what is run is:
products-ui->adminusers
selfservice->adminusers
We really only want to run selfservice->adminusers in this case.
This commit will allow a dynamic creation of the test suite to run based on a
CONSUMER system property. This will mean shorter run times when a provider
contract test is run as part of a specific consumer build.
* Added …
=> PP-5670: Specify the consumer when running contract test

ruleset.xml, src/main/java/uk/gov/pay/adminusers/app/healthchecks/MigrateToInitialDbState.java, src/main/java/uk/gov/pay/adminusers/app/util/RandomIdGenerator.java, src/main/java/uk/gov/pay/adminusers/exception/ValidationException.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/main/java/uk/gov/pay/adminusers/utils/telephonenumber/TelephoneNumberUtility.java, src/main/java/uk/gov/pay/adminusers/validations/RequestValidations.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/InviteExpiryTest.java, src/test/java/uk/gov/pay/adminusers/resources/HealthCheckResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateServiceIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateUserIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceGovUkPayAgreementResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceStripeAgreementIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateNameIT.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java
Add PMD’s Java “Error prone” rules, less the ones we don’t want to bother us (some comments in the rule set explaining why).
Modify code so it doesn’t violate the PMD rules (see individual commits for details).
Some of the rules introduced are broken by our existing code but have not been fixed (and will thus make Codacy complain about this PR). They’re real problems we want to fix but too complicated to tackle in this PR.
=> Add PMD Java “Error Prone” rules

docker-startup.sh, env.sh, shellcheckrc
Fix or ignore errors in shell scripts found by ShellCheck.
ShellCheck reads a shellcheckrc file in the project directory, which can contain directives like `disable=SC2059` to ignore certain errors.
Add a `shellcheckrc` file with no directives (so far, everything we’ve wanted to ignore has been best dealt with on a case-by-case basis) for the benefit of Codacy.
=> Introduce ShellCheck

shellcheckrc
Remove the `shellcheckrc` file, which provides directives to ShellCheck. It was mostly added for Codacy but it appears Codacy does not use this configuration file.
=> Remove shellcheckrc file because Codacy doesn’t use it

.hadolint.yaml, Dockerfile
Use `COPY` rather than `ADD` in `Dockerfile` and add Hadolint (Haskell Dockerfile Linter) configuration to ignore some rules we don’t want to to bother us.
=> Introduce Hadolint

src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/model/Link.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java
- Change `Link.Rel` enum values to upper case as per convention.
Ran PMD locally and fixed the final lint warning.
=> BAU Codacy clean up

src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
When there is an exception sending a notification, the
`uk.gov.service.notify.NotificationClient` will log an error. So there is no
need for us to rethrow a RuntimeException which will also be logged. This is
causing duplicate issues in Sentry. For example,
https://pay-sentry.cloudapps.digital/sentry/adminusers/issues/299/ and
https://pay-sentry.cloudapps.digital/sentry/adminusers/issues/300/ are the same
error - they have the same sentry threadname dw-25. Similarly for
https://pay-sentry.cloudapps.digital/sentry/adminusers/issues/1242/ and
https://pay-sentry.cloudapps.digital/sentry/adminusers/issues/1241/.
=> PP-5809: Don't throw runtime exception on failure to send notification

src/main/java/uk/gov/pay/adminusers/service/UserOtpDispatcher.java
Lowering the level here as there's nothing we can do when a 2fa token can't be
sent. This will already be logged at ERROR level by the notify client as well.
=> PP-5809: Lower log level when 2fa token could not be sent

src/main/java/uk/gov/pay/adminusers/service/EmailService.java
When this happens it's probably because the service wasn't onboarded correctly.
From the application's point of view, this doesn't represent a serious issue.
=> PP-5809: Lower log level for missing merchant details

src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceResetSecondFactorIT.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
Adds an API endpoint for resetting the second factor method to SMS and
generating a new OTP key in the process.
For the case that the second factor method is already SMS, we do nothing
and return a success response.
=> PP-5313 Add reset second factor endpoint

pom.xml, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/test/java/uk/gov/pay/adminusers/infra/DropwizardAppWithPostgresRule.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/DaoTestBase.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceStripeAgreementIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Upgrades dropwizard to v2.0.0
- Added `dropwizard-dependencies` as parent as v2.0.0 upgrade doesn't specify transitive dependency versions anymore https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html
We can also include BOM for transitive dependency versions but versions can't be overridden and we may end up with multiple revisions of same library. For example, `jackson-version` current used is `2.10.2` but dropwizard uses `2.10.1`
- Upgraded dropwizard-sentry library too without which builds are failing with error `java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList org.dhatim.dropwizard.sentry.logging.SentryAppenderFactory.getFilterFactories()'`
- Upgrade pay-java-commons library which is on dropwizard v2.0.0 and defines required …
=> PP-6001 Upgrade Dropwizard

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/service/NotifyClientProvider.java, src/main/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/UserOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/NotificationServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
Change `NotificationService` so that when the `sendSecondFactorPasscodeSms(…)` method is called, an enum constant from the new `OtpNotifySmsTemplateId` enum type is passed in to indicate which Notify template ID to use.
For now, all callers of this method pass in the `LEGACY` enum constant, which maps to the long-serving Notify template ID, so there’s no behaviour change yet.
In subsequent commits, different templates will be chosen for different types of messages and `LEGACY` will be removed.
Also add unit tests for `NotificationService` because there weren’t any and the logic is becoming a bit more complex now. This required some tweaks to how `NotificationService` is instantiated to make it easier to inject mock dependencies.
=> PP-6000 Allow choosing the Notify template for sending OTP via SMS

src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
Move the `newSecondFactorPasscode(…)` method from `UserServices` to the new `ExistingUserOtpDispatcher` class. No functionality changes.
=> PP-6000 Move newSecondFactorPasscode from UserServices to new class

src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserOtpDispatcher.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserOtpDispatcherTest.java
When sending an OTP code to an existing user (not a user who is in the process of creating their account), use the new specific Notify template IDs for the two possible activities: signing in or
changing the sign-in method to SMS.
Note that the actual contents of the messages are the same for now but this allows them to diverge in the future (which we’ll do when nothing is using the legacy template ID).
This change subtly changes the semantics of what it means to send an OTP for a user. Previously, the only difference was whether the provisional OTP key was used or not. Now this also implies whether the user is signing in or changing their sign-in method to SMS and affects the message content, so adjust some naming to clarify this.
=> PP-6000 Specific templates for sign in v change sign-in method SMS

src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteTypeConverter.java, src/main/java/uk/gov/pay/adminusers/service/InviteRouter.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/InviteTypeConverterTest.java
Make the `InviteEntity` type field an `InviteType` and not a `String.` Also make its the `InviteEntity` `getType()` method return an `InviteType` not a `String`. Use `InviteEntity`’s existing `isUserInvite()` and `isServiceInvite()` methods rather than `getType()` in some places.
This means that any `InviteEntity` that is loaded from the database and has a type that isn’t “user” or “service” will blow up during deserialisation but there are no such entities in the production database and other things would probably break if there were.
=> PP-6000 Make InviteEntity type field an InviteType not String

src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcher.java, src/main/java/uk/gov/pay/adminusers/service/UserOtpDispatcher.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserOtpDispatcherTest.java
When sending an OTP code for user who is trying to create a new account (not a user who already has an account), use the new specific Notify template IDs for the two possible variations:
self-initiated user and service creation or creating a user in response to an invitation to join a service.
Note that the actual contents of the messages are the same for now but this allows them to diverge in the future (which we’ll do when nothing is using the legacy template ID).
=> PP-6000 Specific templates for different types of user creation SMS

src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/service/NotificationServiceTest.java, src/test/resources/config/test-it-config.yaml
Remove the legacy Notify OTP SMS template ID now that we have specific ones for specific circumstances.
=> PP-6000 Remove legacy Notify OTP SMS template ID

README.md, docs/api_specification.md
Update README to reflect that `NOTIFY_2FA_TEMPLATE_ID` is no more and add some docs for `/v1/api/users/{externalId}/second-factor`, which had docs before.
=> PP-6000 Update README with OTP SMS changes

Dockerfile
WHAT YOU DID
Updated the the root CA certificate in the container build in preparation for updating the certs installed on the RDS instances.
The combined cert bundle URL does not need to be updated as the URL has not changed, but the updated bundle will be downloaded at build time.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
How to test
Rebuild containers and deploy to test environment
Ensure app works with NEW CA root cert but OLD RDS certs. The new ca certs must be backward compatible.
Schedule the cert update on the RDS instance.
See similar PR for connector
https://github.com/alphagov/pay-connector/pull/2026
=> PP-5920 Update RDS Cert

dev.yml, manifest.yml
This adds a PaaS `manifest.yml` and a `dev.yml` suitable for pushing the
app to dev environments.
Usage:
cf push --vars-file dev.yml \
--var adminusers_url=http://adminusers-dev-<you>.apps.internal:8080 \
--var adminusers_route=adminusers-dev-<you>.apps.internal \
--var selfservice_url=https://pay-selfservice-dev-<you>.london.cloudapps.digital \
--var space=dev-<you>
- Push adminusers to your own PaaS dev environment
- Check adminusers starts and runs successfully
=> PP-6029: Add PaaS manifest

src/main/resources/env-map.yml
The location of the DB credentials will change within VCAP_SERVICES if
the database is a postgres rds instance provided as a cf service
(under 'postgres'), or a container which we use in dev spaces (under
'user-provided').
'env-map.yml' should use the service name which should always be 'adminusers-db'
regardless of the environment.
```
gds5062 > cf push -f manifest.yml --vars-file /Users/danworth/projects/gds/pay-omnibus/paas/env_variables/staging.yml
gds5062 > cf ssh adminusers -c "/tmp/lifecycle/shell /home/vcap/app 'env | sort'" | grep DB
```
The above queries return the correctly set env vars.
=> PP-6085 Lookup DB creds using the service name within env-map.yml

src/main/resources/env-map.yml
Specify the `app-catalog` service as the location for extracting app
urls from within `VCAP_SERVICES`. This should avoid future confusion if
more user provided services are bound to adminusers.
=> PP-6085 Amend env-map to specify app-catalog service

src/main/resources/migrations/00058_add_column_experimental_features_enabled.sql
Allow services to opt into features in development without making specific
flags each time. 
Database migration for, default false, experimental features flag. 
Future improvements may allow generic JSONB flags to be
set on a column.
=> PP-6152 Add `experimental_features_enabled` flag to services

src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceUpdateTest.java, src/test/resources/fixtures/resource/service/patch/replace_experimental_features_enabled_to_true.json
Update service updater to allow `experimental_features_enabled` to
respond to the `update` PATCH request, enforcing a boolean value.
=> PP-6152 Allow PATCH on experimental features flag

manifest.yml, src/main/resources/env-map.yml
Set the `METRICS_HOST` and `METRICS_PORT` from the app-catalog to send
metrics to the carbon-relay app.
=> PP-6254: Add Carbon Relay metrics config

src/test/java/uk/gov/pay/adminusers/pact/ProductsUIContractTest.java, src/test/java/uk/gov/pay/adminusers/pact/SelfServiceContractTest.java
We're using a different pact broker for ci on concourse so make it
configurable, the default is the existing broker used by Jenkins.
=> PP-6445 Make Pact Broker Host configurable

src/main/resources/migrations/00061_add_stripe_account_details_permission.sql, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java
- Added new permission `stripe-account-details:update` so users with this permission can be shown Stripe account status in selfservice
=> PP-6633 Add Stripe account update permissions

pom.xml, src/main/java/uk/gov/pay/adminusers/model/Role.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/RoleEntity.java, src/test/java/uk/gov/pay/adminusers/fixtures/RoleDbFixture.java, src/test/java/uk/gov/pay/adminusers/model/UserEntityTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
Use sets rather than lists for permissions on roles. It doesn’t make sense to have the same permission more than once, so a set is a better fit than a list.
This also allows us to stop using Apache Commons Collections’ `isEqualCollection(…)` method, which allows us to remove the dependency on Commons Collections altogether.
We were explicitly overriding Commons Validator’s dependency on Commons Collections with our own but both Commons Validator and us were depending on the same 3.2.2 version so removing this exclusion will have no effect.
Inspired by https://github.com/alphagov/pay-adminusers/pull/775/commits/2fe336f99541c64503dabe624321ba408d859e3e by @rhowe.
=> BAU — Use sets rather than lists for permissions on roles

src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceGetIT.java
commons-lang isn't actually declared as a dependency so it's a bit naughty to rely on it being there. Switch to commons-lang3, which we do depend on.
Originally contributed by @rhowe in https://github.com/alphagov/pay-adminusers/pull/776.
=> Replace Apache commons-lang with commons-lang3

src/main/resources/migrations/00062_add_services_reporting_columns.sql
- Add `internal` column to indicate whether the service was created for internal testing purposes.
- Add `archived` column to indicate that a service is not in use. Currently this is just for reporting purposes but we could use this in future to affect visibility of a service.
- Add `created_date` column to record the date when the service was created.
- Add `went_live_date` column to record the date when the service was made live.
=> PP-6257 Add reporting columns to services table

pom.xml, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java
Make tests easier to read by using parameterized tests.
Add tests for "gateway_account_id" path validation.
Make validation message consistent when value is null or missing.
=> PP-6257 Refactor service update validator tests

src/test/java/uk/gov/pay/adminusers/model/ServiceNameTest.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/InviteTypeConverterTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteUserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java
- Uses `assertThrows` for asserting exceptions instead of annotation specification (like `@Test (expected = ServiceNotFoundException.class)`) which is not supported anymore in JUnit5
=> PP-6708 Use assertThrows for asserting exceptions

pom.xml, src/main/java/uk/gov/pay/adminusers/service/EmailService.java
- The pom references the dropwizard-dependencies as a parent which includes an execution rule for maven-dependency plugin:analyze-only setting the failOnWarning to true (the default is false). This plugin is run as part of the verify phase. We have undeclared transitive dependencies so the analyze-only goal fails and consequently the build.
- also fix import for ServiceNotFoundException
=> BAU fix mvn verify

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java
Make the allowed public sector email domains be string literals in the list rather than regular expressions because it makes them easier to read and edit.
=> BAU — Make allowed email domains be string literals in lists

Dockerfile
Description:
- This PR updates the docker image to 11.0.9
- From [here](https://hub.docker.com/layers/adoptopenjdk/openjdk11/jre-11.0.9_11.1-alpine/images/sha256-58254737530df7f7e7acfe3e7538a027f898ac05accd2e15adcef34d5a33ae72?context=explore)
=> PP-7283 - Upgrade docker image to 11.0.9

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceCreateIT.java
`created_date` column already exists with a default, but as it is a nullable column the value was set to the null value on the ServiceEntity, as we are using JPA for entity management.
Fix this by adding a default value of `now()` on the ServiceEntity. Add an integration test to ensure a `created_date` is set and returned.
=> PP-7458 Capture created date for services

.secrets.baseline, src/main/java/uk/gov/pay/adminusers/model/ServiceUpdateRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/CustomBrandingConverter.java, src/test/java/uk/gov/pay/adminusers/model/CreateUserRequestTest.java, src/test/java/uk/gov/pay/adminusers/model/ServiceUpdateRequestTest.java, src/test/java/uk/gov/pay/adminusers/model/UpdateMerchantDetailsRequestTest.java, src/test/java/uk/gov/pay/adminusers/model/UserEntityTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/resources/EmailResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/GovUkPayAgreementRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/HealthCheckResourceTest.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteUserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceGovUkPayAgreementResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceStripeAgreementIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateNameIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateServiceRoleIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourcePatchIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceUpdateServiceRoleIT.java, src/test/java/uk/gov/pay/adminusers/service/LinksBuilderTest.java, src/test/java/uk/gov/pay/adminusers/service/UserOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java, src/test/java/uk/gov/pay/adminusers/utils/ErrorsTest.java
ObjectMapper is an expensive object so reduce its instantiation.
Also remove [some] unnecessary `public` qualifiers not needed for junit5 tests.
=> bau: Reduce ObjectMapper instantiation

.secrets.baseline, src/test/java/uk/gov/pay/adminusers/resources/UserResourceAuthenticationIT.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java
Stop checking the exact number of permissions a user has in tests. Checking the exact number means the test breaks every time we add a new permission (which is a database migration, not a code change). Just check there‘s at least one permission instead.
=> PP-7708 Don’t check exact number of permissions in tests

src/main/resources/migrations/00064_add_agent_initiated_moto_enabled_to_services.sql, src/main/resources/migrations/00065_add_agent_initiated_moto_create_permission.sql, src/main/resources/migrations/00066_add_view_and_intiate_moto_and_view_refund_and_intiate_moto_roles.sql
- Add `agent_initiated_moto_enabled` boolean column to services table with default value of false
- Add `agent-initiated-moto:create` permission, granting it to the `admin` role
- Add new `view-and-initiate-moto` role, giving it the same permissions as `view-only` and also `agent-initiated-moto:create`
- Add new `view-refund-and-initiate-moto` role, giving it the same permissions as `view-and-refund` and also `agent-initiated-moto:create`
Tested locally and it did what I expected.
=> PP-7708 Database migrations for agent-initiated MOTO payments

src/main/java/uk/gov/pay/adminusers/model/PspTestAccountStage.java, src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Keeping track of the new feature of services asking for a non sandbox test account (PSP specific)
- add the new field `current_psp_test_account_stage` to Service and ServiceEntity objects.
- update patch journey for the new field
- update/create relevant tests
=> PP-7765 add psp test account field to service

src/main/resources/migrations/00069_add_psp_test_account_stage_permission.sql
- replace underscore with hyphen in permission's name
=> PP-7765 correct psp test account permission name

src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/InviteFinder.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java, src/test/java/uk/gov/pay/adminusers/utils/ComparatorsTest.java
Replace `Collectors.toList()` with `Collectors.toUnmodifiableList()` and `Collectors.toMap()` with `Collectors.toUnmodifiableMap()` respectively, making adjustments where necessary to handle the fact that the latter methods return unmodifiable collections.
See individual commit messages for details.
=> PP-7964 Replace Collectors.toList() with Collectors.toUnmodifiableList()

pom.xml
We will not be using Bintray for long but we should use HTTPS where we can.
This brings adminusers in line with connector and prepares us for Maven 3.8.1, which will refuse to download dependencies over HTTP by default.
=> BAU — Use HTTPS for Bintray repository for GOV.UK Notify dependency

src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/main/java/uk/gov/pay/adminusers/utils/CountryConverter.java
Replace `Collectors.toMap()` with `Collectors.toUnmodifiableMap()`.
The returned maps are never modified and will never contain nulls.
=> PP-7964 Replace Collectors.toMap() with Collectors.toUnmodifiableMap()

src/main/java/uk/gov/pay/adminusers/persistence/entity/UTCDateTimeConverter.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/StripeAgreementDaoIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Make `ServiceDaoIT.shouldFindByServiceExternalId()` pass when computer time zone is British Summer Time (+0100).
The test inserts a test into the database, retrieves it using the `ServiceDao` and then asserts that the created date of the service is within 5 seconds of the current time. When the test runs on a computer using BST as its time zone, it fails because the created date is an hour earlier than the actual current time.
For example, if it is 15:00 BST, the test expects the created date of the service to be 14:00 UTC (which is the same time because BST is an hour ahead of UTC). However, the created date is 13:00 UTC.
I am not sure why this is. The service is inserted into the database directly using JDBI. The created date is stored in a column with a type of `TIMESTAMP WITH TIME …
=> BAU — Make integration test pass when computer time zone is BST

pom.xml
Remove reference to bintray so that the GOV.UK Notify client is downloaded from Maven Central.
=> PP-7995 Download Notify client from Maven Central

.github/dependabot.yml
Add "dependencies" label as it isn't added by default despite what the documentation says
=> PP-7904 Amend dependabot.yml

src/main/resources/migrations/00072_alter_table_services_add_column_default_billing_address_country.sql
Add column default_billing_address_country to services table and default to "GB". At this stage the only expected values would be "GB" or null.
=> PP-8445 Add default_billing_address_country to services

src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/service/ServiceCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserCreatorTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceFindTest.java
Read the value from the database and return the field `default_billing_address_country` in the service object in API responses.
Set the default country as "GB" when creating services.
=> PP-8445 Return default_billing_address_country in service responses

Jenkinsfile
Jenkins CI no longer needs to deploy the original ECS version so skip
this step.
Removing pact tagging and checking is next
=> PP-8695 Remove Deploy step

.secrets.baseline, src/main/java/uk/gov/pay/adminusers/model/InviteServiceRequest.java, src/main/java/uk/gov/pay/adminusers/resources/InviteRequestValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/test/java/uk/gov/pay/adminusers/resources/InviteUserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java
Stop requiring a phone number and password to be specified when we get a request from selfservice to create a service invite so that we can eventually only set the phone number and password on the invite after it’s created.
Currently, selfservice’s validation will stop us from ever receiving a request to create a service invite that does not have a phone number and a password.
=> PP-8728 Do not require password and phone for service invite

src/main/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcher.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGenerateOtpIT.java, src/test/java/uk/gov/pay/adminusers/service/InviteRouterTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserOtpDispatcherTest.java
If a request is sent to `/v1/api/invites/{code}/otp/generate` with the following body:
```json
{
"telephone_number": "07700900000",
"password": "password123"
}
```
… and the code relates to a service invite (that is, one where the user is signing up on their own initiative without receiving an invitation to join a service) then update the phone number and password on the invite with the provided values before sending the one-time password.
This makes `ServiceOtpDispatcher` behave similarly to `UserOtpDispatcher` (the equivalent for user invites — that is, where
a user is signing up because they have been invited to a service) except the `"telephone_number"` and `"password"` properties are optional for `ServiceOtpDispatcher`.
This prepares us for a world where service invites only have the …
=> PP-8728 Set phone and password on service invite when sending OTP

src/main/java/uk/gov/pay/adminusers/model/MerchantDetails.java, src/main/java/uk/gov/pay/adminusers/model/UpdateMerchantDetailsRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/MerchantDetailsEntity.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceUpdateOperationValidator.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUpdater.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/MerchantDetailsEntityBuilder.java, src/test/java/uk/gov/pay/adminusers/resources/EmailResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceUpdateMerchantDetailsIT.java, src/test/java/uk/gov/pay/adminusers/service/EmailServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUpdaterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Return field in get one service or search services API endpoints
- Accept new field url on PUT /{serviceExternalId}/merchant-details (url is not mandatory)
- Allow patching field url on PATCH /{serviceExternalId}
=> PP-8800 add url to update merchant details

src/main/resources/migrations/00076_add_stripe_government_entity_document_permissions.sql
- Add `update` permissions for Stripe government entity document upload task.
=> PP-8962 Add permissions for government entity document upload task

src/test/java/uk/gov/pay/adminusers/pact/ProductsUIContractTest.java, src/test/java/uk/gov/pay/adminusers/pact/SelfServiceContractTest.java
The purpose of running the provider contract test is to ensure the app can be
deployed to the test environment without breaking its contractual obligations
with other apps. Pacts are tagged with 'test-fargate' in the concourse deploy
pipeline for app deployments so this tag needs to be updated.
=> bau: Use 'test-fargate' when running provider contract test

src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/client/ledger/model/LedgerTransaction.java, src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/EventType.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetails.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/service/ServiceFinder.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/main/java/uk/gov/pay/adminusers/utils/currency/ConvertToCurrency.java, src/main/java/uk/gov/pay/adminusers/utils/date/DisputeEvidenceDueByDateUtil.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/fixtures/LedgerTransactionFixture.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueueTest.java, src/test/java/uk/gov/pay/adminusers/service/NotificationServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceFinderTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java, src/test/java/uk/gov/pay/adminusers/utils/currency/ConvertToCurrencyTest.java, src/test/java/uk/gov/pay/adminusers/utils/date/DisputeEvidenceDueByDateUtilTest.java, src/test/resources/config/test-it-config.yaml
Added a new handler method to the EventMessageHandler to process Dispute events. Adminusers now contacts Ledger for the transaction reference related to the dispute, looks up the service, identifies the admin users and constructs the relevant details before sending an email using the new dispute template in Notify.
The template ids in the application config have been updated to include the new template id and the support reply address id, the notification service has been updated to support including an alternative reply address.
=> PP-9279 implement dispute handling in Adminusers

.github/workflows/_run-pact-provider-tests.yml
Add reusable workflow for adminusers-as-provider pact tests. This is the same code as in connector and ledger but for adminusers
- See the test workflow in frontend https://github.com/alphagov/pay-frontend/runs/5535387251?check_suite_focus=true (this sets the consumer as selfservice, not frontend, but frontend is the only repo set up so far to be able to execute these and with the pact secrets)
N/A
N/A
=> PP-9379: Add adminusers as provider pact test reusable workflow

.github/workflows/_run-pact-provider-tests.yml
This is a speculative fix for the Pact Provider tagging issue that we've picked-up. We've discovered that when the workflow is called by other Pact consumers to use Adminusers as the "provider", it re-uses the same Git SHA from the consumer, which is undesired behaviour.
At present, the Checkout Action does not provide an output for this, so we're using a workaround.
Thanks to @jfharden and @katstevens for helping to figure this out.
=> [BAU] Speculative fix for Pact Provider Tagging

src/main/java/uk/gov/pay/adminusers/queue/managed/EventSubscriberQueueMessageReceiver.java
The EventSubscriberQueueMessageReceiver wasn't correctly getting the
eventSubscriberQueueEnabled flag from the application configuration to
determine whether to poll for messages.
=> PP-9259 Enable event processing if flag enabled in config

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetails.java, src/test/java/uk/gov/pay/adminusers/TestTemplateResourceLoader.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetailsTest.java, src/test/resources/templates/events/dispute_created_event.json
- Added additional logging to the event message handler to log information regarding processed notification emails for disputes
- Fixed a bug in DisputeCreatedDetails where a Json property was incorrectly labelled
- Added missing deserialisation test for Dispute Events
=> PP-9279 Additional logging, model tests and deserialisation bug fixes

src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/ForgottenPasswordServicesTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java
Log the exception message when sending an email fails.
Pass along the original exception when throwing a
WebApplicationException so that more information gets to Sentry.
=> PP-9279 Log exceptions from Notify better

src/main/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueue.java, src/main/java/uk/gov/pay/adminusers/queue/model/SNSMessage.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueueTest.java
Event message is contained as an escaped string inside the "Message" field of an SNS message. Fix deserialisation to deal with this.
=> PP-9278 Fix deserialisation of SNS message

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java, src/test/java/uk/gov/pay/adminusers/utils/email/EmailValidatorIsPublicSectorEmailTest.java
Allow emails from the domain achievingforchildren.org.uk to create
accounts. Reference ZD#4919143.
=> ZD4919143 Add `achievingforchildren.org.uk` domain to email allow list

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java
Remove the comma to adhere to the GOV.UK style guide
https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#dates
=> PP-9281 Fix date format in dispute email

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/Event.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetails.java, src/test/java/uk/gov/pay/adminusers/fixtures/EventFixture.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueueTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetailsTest.java
Due to issues with how ledger is projecting transactions from events,
there is a bug where the service_id on a transaction is overwritten to
null when an event, such as PAYMENT_INCLUDED_IN_PAYOUT doesn't send a
service_id.
This means that for now at least we have to rely on the
gateway_account_id, which is also sent in the event details to look up
the service.
=> PP-9281 Look up service by gateway account id

src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/resources/ToolboxEndpointResource.java, src/main/java/uk/gov/pay/adminusers/service/ServiceUserRemover.java, src/test/java/uk/gov/pay/adminusers/resources/ToolboxEndpointResourceIT.java, src/test/java/uk/gov/pay/adminusers/service/ServiceUserRemoverTest.java
Given that users need to be in the alphagov organisation in GitHub in order to
be authenticated with toolbox, it should be fairly safe to expose an endpoint
to remove a user from a service without requiring a "GovUkPay-User-Context"
header. Note that the original `DELETE
/v1/api/services/{serviceExternalId}/users/{userExternalId}` endpoint is still
valid and is used by selfservice. In order to make it clear `DELETE
/v1/api/toolbox/services/{serviceExternalId}/users/{userExternalId}` is for
toolbox use only we've placed the implementation in
ToolboxEndpointResource.java for clarity.
=> PP-8827: Endpoint to remove user from service

.gitignore, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/ServiceSearchRequest.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/ServiceFinder.java, src/main/resources/migrations/00077_alter_table_service_names_add_fts_index.sql, src/main/resources/migrations/00078_alter_table_services_add_fts_index.sql, src/test/java/uk/gov/pay/adminusers/model/ServiceSearchRequestTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceFinderTest.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceSearchTest.java, src/test/resources/fixtures/resource/service/post/service-search-request.json
- added a new POST endpoint for looking up services by their name or associated merchant name
- created two new indices on the `service_names` and `services` tables to improve text search performance on the `name` and `merchant_name` columns
- created new lexeme based vector queries to provide text search in the service dao
=> PP-9443 New toolbox search endpoint for services

src/main/resources/migrations/00079_add_agreement_permission.sql
Agreements read and update permissions are currently mapped similarly to
the transactions case worker model. As services start using it if they
need more granular permissions this can be reconsidered.
=> PP-9541 Add initial agreements permissions

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeLostDetails.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeLostDetailsTest.java, src/test/resources/templates/events/dispute_lost_event.json
- refactor DISPUTE_LOST event handling to use gateway account id. This is needed because disputes can be opened up to 120 days and sending service id was only fixed on 24/03
- also refactor a few code repetitions
- refactor tests as well
=> PP-9576 refactor dispute lost event handling

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java
- Do not throw exception when email sending is not yet enabled. Just log the issue.
- Update tests.
=> PP-9576 refactor dispute event handling

.github/dependabot.yml, pom.xml
- The Github UI is giving critical warnings for our Java apps with liquibase below v4.8.0. Patched liquibase to 4.12.0
- Thus ignoring liquibase is no longer required, remove it from dependabot yaml file.
=> PP-9620 update liquibase

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/service/UserServices.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
- Refactored EventMessageHandler
- to make logging consistent for all dispute events
- extracted common tasks (get a transaction, send email to admins) for all dispute events into their own methods
=> PP-9622 Refactor EventMessageHandler

src/main/java/uk/gov/pay/adminusers/app/config/NotifyConfiguration.java, src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/service/NotificationServiceTest.java, src/test/resources/config/test-it-config.yaml
The NotificationService chooses between two different templates based on whether the personalisation info includes details of a fee.
=> PP-9841: Use different Notify template when a lost dispute has a fee

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/EventType.java, src/test/java/uk/gov/pay/adminusers/queue/model/EventTypeTest.java
- Handle unknown event types better. The current way of getting EventType enum throws an exception if an event type is not in enum constants
=> PP-9671 Handle unknown event types

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetails.java, src/main/java/uk/gov/pay/adminusers/utils/dispute/DisputeReasonMapper.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetailsTest.java, src/test/java/uk/gov/pay/adminusers/utils/dispute/DisputeReasonMapperTest.java
- Add the new personalisation content variables to sending a dispute created email. Going to remove the unused ones in the next iteration, once the new template has been enabled.
=> PP-9670 refactor sending dispute created email personalisation

src/main/java/uk/gov/pay/adminusers/queue/event/EventMessageHandler.java, src/main/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueue.java, src/main/java/uk/gov/pay/adminusers/queue/model/Event.java, src/test/java/uk/gov/pay/adminusers/fixtures/EventFixture.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventMessageHandlerTest.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueueTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeCreatedDetailsTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeEvidenceSubmittedDetailsTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeLostDetailsTest.java, src/test/java/uk/gov/pay/adminusers/queue/model/event/DisputeWonDetailsTest.java, src/test/resources/templates/events/dispute_created_event.json, src/test/resources/templates/events/dispute_evidence_submitted_event.json, src/test/resources/templates/events/dispute_lost_event.json, src/test/resources/templates/events/dispute_won_event.json, src/test/resources/templates/sns/dispute_created_sns_message.json
Ledger was previously re-serialising events to send to SNS with the
`event_details` value as an escaped JSON string.
This has been changed so that the event processed by ledger is directly
passed on without deserialising and then re-serialising the event
message in a way that transformed the `event_details` in this way.
=> PP-9292 Fix deserialisation of events

pom.xml
* Bump dropwizard from 2.0.29 to 2.0.33.
* This fixes a low severity vulnerability reported by Snyk (CVE-2022-2047).
* The vulnerability is fixed in 2.0.32, but we may as go as far as we can within this major version.
* PP-9562 suggests it would not be trivial to update to 2.1.x.
=> BAU: Update dropwizard to 2.0.33

.pre-commit-config.yaml, .secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/SearchServicesResponse.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/ServiceFinder.java, src/test/java/uk/gov/pay/adminusers/service/ServiceFinderTest.java
The OpenApi schema for the search services response was incorrectly stating that the response was an array of services. However, it actually returns an object with two fields: `name_results` and `merchant_results`
Fix this by creating a Java class to represent the response, rather than returning a Map and use this as the schema for the OpenApi spec.
Regenerated .secrets.baseline file using version 1.2.0 of detect-secrets, as used by other repositories.
=> PP-9814 Fix the OpenApi spec for search services

src/main/java/uk/gov/pay/adminusers/model/InviteType.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteRouter.java, src/main/java/uk/gov/pay/adminusers/service/InviteServiceFactory.java, src/main/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleter.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteRouterTest.java, src/test/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleterTest.java
* Add new InviteType constants, which will replace the old ones (the new ones have better names and cover the full range of journeys).  This PR adds the new constants but does not start using them.
* Rename the InviteCompleter implementations to reduce ambiguity, and add new InviteCompleter to handle the 'new user, existing service' journey.
=> PP-10041: Add new InviteType constants and refactor invite completers

src/main/java/uk/gov/pay/adminusers/model/InviteType.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteRouter.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/test/java/uk/gov/pay/adminusers/persistence/entity/InviteTypeConverterTest.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteRouterTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteServiceTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/ServiceOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserOtpDispatcherTest.java
Before we can switch over to using the new values, we need to update the places where they are used:
* Remove isServiceType() and isUserType() methods from InviteEntity
* Temporarily replace the above with isSelfService() and isExistingUserExistingService methods on InviteType - we will get rid of these once the old enum values no longer need to be handled
* Use the enum values (old and new) to choose which InviteOtpDispatcher to use in InviteRouter
* Also, refactor InviteRouter a bit to get rid of a pointless Optional type
* Map the new enum values to Notify templates for sending OTP SMS messages 
* Support use of the new enum values in InviteService
* Add test coverage for the new enum values
=> PP-10041: Prepare to switch to new InviteType constants

.secrets.baseline, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteRouter.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleter.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGenerateOtpIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceUserCompleteIT.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/InviteRouterTest.java, src/test/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
PP-10041 Refactor InviteRouter#routeOtpDispatch
Refactor the InviteRouter#routeOtpDispatch to accept an InviteEntity
rather than a code. Instead, look up the InviteEntity in the resource.
This simplifies the code as InviteRouter#routeOtpDispatch no longer
needs to return a Pair with a boolean indicating whether or not the
telephone number and password should be expected in the HTTP request
body.
PP-10041 Refactor invite completer
Refactor invite completer resource so that the resource gets the
InviteEntity once and passes it to the code that needs to use it. This
avoids having to look up the invite multiple times and also simplifies
return types.
with @alan-gds
=> PP-10041 refactor getting invite

src/main/java/uk/gov/pay/adminusers/persistence/entity/UserEntity.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserOtpDispatcher.java, src/test/java/uk/gov/pay/adminusers/model/UserEntityTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserOtpDispatcherTest.java, src/test/java/uk/gov/pay/adminusers/service/UserServicesTest.java
The `telephone_number` column on the `users` table is going to be made nullable. Prepare for this by returning an Optional from the getter on the UserEntity, and handling it not being present by throwing an exception that is mapped to a 412 error response.
=> PP-10048 Prepare for telephone number being nullable

src/main/resources/migrations/00081_alter_users_set_telephone_number_nullable.sql
Make the telephone_number column on the users table nullable. This is to allow for users to sign-up to pay with authenticator apps, which will not require them to enter a phone number.
=> PP-10048 Make telephone number nullable on users

src/main/java/uk/gov/pay/adminusers/service/ServiceInviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/test/java/uk/gov/pay/adminusers/service/ServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java
Start using the new InviteType enum values.  The old values will still be present in the database on older invites, until they either expire after 2 days or we do a migration - so, we're not removing support for the old values yet.
=> PP-10041: Start using new InviteType enum values

src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceOtpIT.java
This is a copy of the existing v1 /otp/validate/service endpoint, which will be removed later once we have switched to using this new one.
=> PP-10041: Add v2 /otp/validate endpoint to InviteResource

.github/workflows/_run-pact-provider-tests.yml, .github/workflows/run-tests.yml, pom.xml, src/test/java/uk/gov/pay/adminusers/infra/AppWithPostgresAndSqsRule.java, src/test/java/uk/gov/pay/adminusers/infra/AppWithPostgresExtension.java, src/test/java/uk/gov/pay/adminusers/infra/SqsTestDocker.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/DaoTestBase.java, src/test/resources/it-migrations.xml
- removed use of `govuk/postgres:11`, baselining on architecture agnostic `postgres:11.16`
- updated test bases and rules to enable cross architecture support
- added integration tests specific liquibase changelog (`it-migrations.xml`) to initialise the database before migrations can be run
- updated local sqs image to be consistent with other Pay applications
- updated GHA to use new images
=> PP-10004 M1 support for integration tests

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/CompleteInviteRequest.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleter.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteIT.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleterTest.java
Accept a POJO in the method signature for deserialising the request body.
Refactor InviteCompleter to remove the `withData` method and instead pass in the CompleteInviteRequest as an argument of `InviteCompleter#complete` to make it easier to understand. The `CompleteInviteRequest` will be null if the request was made with no body.
=> PP-10260 Refactor complete invite resource

src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/UserInviteCreator.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/UserInviteCreatorTest.java
An InviteEntity doesn't have a service set on it if it is for a self-registration. Make the getter for the service return an Optional to ensure we do null checks correctly.
Currently an InviteEntity always has a role set. However, this will not need to be set in the future for self-registration. It was used to set the role when creating a new test service - which was always the admin role. But will not be used when a service is no longer created as part of a self-registration so shouldn't be set on the invite in this case.
=> PP-10244 Make service and role Optional on InviteEntity

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/CompleteInviteRequest.java, src/main/java/uk/gov/pay/adminusers/model/CompleteInviteResponse.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/main/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/InviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleter.java, src/main/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleter.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceServiceCompleteIT.java, src/test/java/uk/gov/pay/adminusers/service/ExistingUserInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/NewUserExistingServiceInviteCompleterTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfSignupInviteCompleterTest.java
The `/v1/api/invites/{code}/complete` endpoint now reads a `secondFactor` value from the request body and passes it on to the InviteCompleter.  The two InviteCompleters that create a new user now add the `secondFactor` to the user entity before it is persisted.
=> PP-10038: Persist 2FA method when creating user

src/test/java/uk/gov/pay/adminusers/pact/ContractTest.java
Amend the pact state that sets up an invite with a telephone number set. This is so that the selfservice Pact test to get an invite can check that the telephone number field is returned in the response.
=> PP-10055 Amend invite exists pact state

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGetIT.java
Include the otp_key in API responses that return an Invite. This is so that the key can be displayed on the selfservice page to set up an authenticator app.
=> PP-10052 Include otp_key in Invite response

src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java
This is required in order for https://github.com/alphagov/pay-selfservice/pull/3652 to work correctly.
=> PP-10280: Default to valid OTP code in `inviteDbFixture`

src/test/java/uk/gov/pay/adminusers/pact/ContractTest.java
Add pact state so we can add a pact to check that is possible to call /v1/api/invites/${inviteCode}/complete without a request body for an invite for an existing user.
=> PP-10052 Add pact state for invite for existing user

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/CreateInviteToJoinServiceRequest.java, src/main/java/uk/gov/pay/adminusers/model/CreateSelfRegistrationInviteRequest.java, src/main/java/uk/gov/pay/adminusers/resources/InviteResource.java, src/main/java/uk/gov/pay/adminusers/service/InviteServiceFactory.java, src/main/java/uk/gov/pay/adminusers/service/JoinServiceInviteCreator.java, src/main/java/uk/gov/pay/adminusers/service/NotificationService.java, src/main/java/uk/gov/pay/adminusers/service/SelfRegistrationInviteCreator.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateInviteToJoinServiceIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateSelfRegistrationInviteIT.java, src/test/java/uk/gov/pay/adminusers/service/JoinServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfRegistrationInviteCreatorTest.java
We want to change the names of these endpoints as follows:
/v1/api/invites/service → /v1/api/invites/create-self-registration-invite /v1/api/invites/user → /v1/api/invites/create-invite-to-join-service
We are adding the new endpoints so that we can later delete the old endpoints once self-service is using the new ones.
The names of some service classes and methods have been updated in line with these changes.
=> PP-10407: Replacement create invite endpoints

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/Invite.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/main/java/uk/gov/pay/adminusers/service/InviteService.java, src/main/java/uk/gov/pay/adminusers/service/SelfRegistrationInviteCreator.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateInviteToJoinServiceIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceCreateSelfRegistrationInviteIT.java, src/test/java/uk/gov/pay/adminusers/resources/InviteResourceGetIT.java, src/test/java/uk/gov/pay/adminusers/service/JoinServiceInviteCreatorTest.java, src/test/java/uk/gov/pay/adminusers/service/SelfRegistrationInviteCreatorTest.java
Endpoints which return an invite will now include this flag, which will soon be used instead of the `type` field, so that we can delete the latter.
=> PP-10338: Add `isInviteToJoinService` to `Invite` object

src/main/resources/migrations/00083_remove_type_column_from_invites.sql, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
Invite types are no longer used, so the column is now redundant.
=> PP-10338: Remove `invite.type` column from database

.github/workflows/_run-pact-provider-tests.yml
Located  and replaced set-output in github actions workflow
=> PP-10675: replaced usage of set-output in run-pact-provider-tests.yml

src/main/java/uk/gov/pay/adminusers/utils/email/EmailValidator.java
Rename `PUBLIC_SECTOR_EMAIL_DOMAIN_REGEX_PATTERNS_IN_ASCENDING_ORDER` to `PUBLIC_SECTOR_EMAIL_DOMAINS` because it’s a list of literal domain names and not a list of regular expression patterns.
=> BAU — Rename public sector email domains variable to be accurate

src/main/resources/migrations/00084_alter_table_users_add_unique_index_lower_email.sql, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java
The current sql unique constraint on the email column in the users table is not case insensitive. It should be.
Unique constraint lower(email) is not valid PSQL script. It was either unique index or installing citext extension and altering the column type. citext can only be installed by superuser and cannot be done through our usual liquibase script.
- Add unique index to lower(email).
=> PP-11265 add unique index to lower email on the users table

src/main/resources/migrations/00085_alter_table_users_remove_username_not_null_constraint.sql
We are removing username column. Before we can drop the column, we need to refactor the code, and that's not possible without dropping the not null constraint
- drop not null constrain for username in users table
=> PP-11283 drop not null constraint

openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/resources/UserRequestValidator.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java, src/main/java/uk/gov/pay/adminusers/service/AdminUsersExceptions.java, src/test/java/uk/gov/pay/adminusers/resources/UserRequestValidatorTest.java, src/test/java/uk/gov/pay/adminusers/resources/UserResourceCreateIT.java, src/test/java/uk/gov/pay/adminusers/service/AdminUsersExceptionsTest.java
We no longer store username, we rely on the user's email. It'd be silly to expect username when creating a new user.
- remove username from user creation requests
- refactor code accordingly
- refactor tests accordingly
=> PP-11327 remove username from create user

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java
Adminusers is searching by email.
It makes sense to rename the payload's field to email instead of username.
- rename username to email in findUser
=> PP-11327 switch using email to find a user

README.md, pom.xml, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersConfig.java, src/main/resources/config/config.yaml, src/test/resources/config/test-it-config.yaml
1. Remove graphite metrics configuration and sending
2. Rename GRAPHITE_SENDING_PERIOD_SECONDS to METRICS_COLLECTION_PERIOD_SECONDS, and set it to the appropriate value.
Check build passes and explicitly wait for the e2e tests to pass
* ~Introduced any new environment variables~ / removed existing environment variable
* ~Added new API / updated existing API definition~
=> PP-11228: Remove graphite metrics sending and config

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/exception/StripeAgreementExistsException.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/StripeAgreementService.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceGovUkPayAgreementResourceIT.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceStripeAgreementIT.java, src/test/java/uk/gov/pay/adminusers/service/StripeAgreementServiceTest.java
When a request was made to create either a GovUkPayAgreement or StripeAgreement was made, we were returning a 409 error if one already existed.
Instead return a 200. For creating a GovUkPayAgreement, also return the agreement in the response.
This is so that we can recover from the scenario where the end user submits the admin tool page to agree to the agreement, but there is another error, which we have seen happen when trying to create the Zendesk ticket.
=> BAU Return success response when agreement exists

build-local.sh, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java
Now we don't need to build our default labels in the app (since they are now added by the sidecar) we should remove the default sample builder.
1. Remove default sample builder
2. Update local build script to account for m1 macs, and use the correct container tag
This change has already been rolled out to connector and is working well.
=> PP-11548: Update prometheus initialisation

Dockerfile
Update docker image JRE to 11.0.20
- Make sure the build succeeds
- Peer reviewed as part of pairing 
- Another team member to review
- Smoke test relevant app or service
Refer to Jira ticket https://payments-platform.atlassian.net/browse/PP-11407 to understand reason for version upgrade.
=> PP-11407: Update docker image JRE to 11.0.20

m1/arm64.Dockerfile
Update docker image JRE to 11.0.20 for M1
- Make sure the build succeeds
- Peer reviewed as part of pairing
- Another team member to review
- Smoke test relevant app or service
Refer to Jira ticket https://payments-platform.atlassian.net/browse/PP-11407 to understand reason for version upgrade.
=> PP-11407: Update docker image JRE to 11.0.20 for M1.

pom.xml
• Upgrade Dropwizard from 3.0.1 to 3.0.2
• Upgrade WireMock from 2.35.1 to 3.2.0
• Use more Maven BOMs for dependencies
• Separate dependencies into those imported from BOMs and others
=> PP-11652 Upgrade from Dropwizard 3.0.1 to Dropwizard 3.0.2

.secrets.baseline, src/main/java/uk/gov/pay/adminusers/model/User.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/UserDao.java, src/test/java/uk/gov/pay/adminusers/fixtures/UserDbFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Added DAO method to delete historic users not associated with any service
- Updated User model for the new field (createdAt) required for tests, as tests and API resources use the same class. To refactor in a separate PR so that tests use separate fixtures.
=> PP-11205 Add DAO method to delete users

.github/dependabot.yml, pom.xml
- Use Dropwizard version property so we upgrade Dropwizard and Dropwizard Testing Support for JUnit 4.x in lockstep
- Use Testcontainers BOM
- Stop using EclipseLink version property because it’s only used in one place
- Remove unused Guice version property
- Tell Dependabot not to try to upgrade us to Guice 7.0.0, which migrates from Java EE to Jakarta EE and is never going to be a just-merge-it upgrade
=> BAU — Small tweaks to POM and Dependabot config

.github/dependabot.yml
Tell Dependabot to ignore Guice 6.x and Dropwizard Sentry 4.x because neither of these are going to be just-merge-the-Dependabot-PR upgrades:
- Guice 6.x requires compatibility work on our side while Guice 7.x only works with Jakarta EE and not Java EE
- We essentially forked Dropwizard Sentry because it did not support Dropwizard 3.x — there is now a Dropwizard Sentry 4.x, which supports Dropwizard 4.x (and maybe Dropwizard 3.x), but we’d need to do work to go back to using an unmodified version
Also add comments explaining why we’re ignoring upgrades for certain Maven dependencies.
=> BAU — Tell Dependabot to ignore Guice 6 and Dropwizard Sentry 4

pom.xml
dependabot will not update dropwizard dependecies because it uses ${dropwizard.version}. dropwizard-testing-junit4 is also using ${drowizard.version} but it's a different module and its version numbering is out of sync with the main dropwizard dependencies. We need the updates for dropwizard dependencies not to rely on io.dropwizard.modules versions for security updates.
- separate the 2 dependencies that each of them have their own versiong.
=> BAU fix dropwizard versioning

README.md, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersConfig.java, src/main/java/uk/gov/pay/adminusers/app/config/ExpungeAndArchiveDataConfig.java, src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java, src/test/resources/config/test-it-config.yaml
- Added service method to delete historical data.
- Currently includes
- Users not attached to any service
- Forgotten passwords
- and Invites
=> PP-11205 Add service method to expunge data

src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceEntityFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Added method to find services to check for archiving
=> PP-11205 Add method to find services

pom.xml
Upgrade notify client 3.19.2 -> 4.1.0
Noteworthy changes in this version:
- Joda-Time has been removed and replaced with java.time
- The client now uses [ZonedDateTime instead of DateTime](https://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html)
=> PP-11711 upgrade notify client 3.19.2 -> 4.1.0

src/main/java/uk/gov/pay/adminusers/app/config/ExpungeAndArchiveDataConfig.java, src/main/java/uk/gov/pay/adminusers/client/ledger/model/LedgerSearchTransactionsResponse.java, src/main/java/uk/gov/pay/adminusers/client/ledger/model/LedgerTransaction.java, src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/main/resources/config/config.yaml, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java, src/test/java/uk/gov/pay/adminusers/fixtures/LedgerSearchTransactionsResponseFixture.java, src/test/java/uk/gov/pay/adminusers/fixtures/LedgerTransactionFixture.java, src/test/resources/config/test-it-config.yaml
- Archive services without any transactions in the last 7 years (or based on config number of days).
- Criteria for archiving service is 
- last transaction (for any linked gateway account) and is older than 7 years
-  OR created date is older than 7 years
- It is possible that a service doesn't have any transaction and created_date is also null. These will be dealt with separately.
=> PP-11205 Archive services

.secrets.baseline, README.md, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java, src/main/java/uk/gov/pay/adminusers/client/ledger/model/LedgerTransaction.java, src/main/java/uk/gov/pay/adminusers/expungeandarchive/resource/ExpungeAndArchiveHistoricalDataResource.java, src/main/java/uk/gov/pay/adminusers/model/Service.java, src/main/resources/openapi-config.yaml, src/test/java/uk/gov/pay/adminusers/expungeandarchive/resource/ExpungeAndArchiveHistoricalDataResourceIT.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceDbFixture.java, src/test/java/uk/gov/pay/adminusers/infra/AppWithPostgresExtension.java, src/test/java/uk/gov/pay/adminusers/infra/LedgerStub.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java, src/test/resources/config/test-it-config.yaml
- Added endpoint to expunge and archive historical data
=> PP-11205 Add endpoint to expunge and archive historical data

src/main/java/uk/gov/pay/adminusers/expungeandarchive/resource/ExpungeAndArchiveHistoricalDataResource.java, src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/resource/ExpungeAndArchiveHistoricalDataResourceIT.java, src/test/java/uk/gov/pay/adminusers/fixtures/InviteDbFixture.java
- Delete forgotten_passwords & invites records first which have foreign key relation to the users table. 
- Delete historical users first could result in a `foreign key constraint violation` if there are references in forgotten_passwords & invites
=> PP-11205 Change the order of deleting user data

src/main/java/uk/gov/pay/adminusers/resources/ServiceRequestValidator.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceRequestValidatorTest.java
Some services - such as King’s Academy have an apostrophe in their name.
- update regex to allow apostrophes and hyphen in service search payload
=> PP-11355 allow apostrophes and hyphens when searching by service name

src/main/resources/migrations/00088_alter_services_add_columns_for_archiving.sql
- Added below columns to use when archiving services
1. `first_checked_for_archival_date`
This date will be set when services are checked for archival and not archived
Will mainly be used to select services for archiving where `created_date is not available` and no transactions exist. Any services with `first_checked_for_archival_date` set and no transaction exists for 7 years from this date will be archived.
2. `skip_checking_for_archival_until_date`
For services taking payments, it won't be necessary to check them for archiving again in about a week's time. So this date can be set and used to skip checking services for archiving for 7 years since the last payment.
=> PP-11205 Add columns to use when archiving services

pom.xml, src/test/java/uk/gov/pay/adminusers/pact/ConnectorQueueMessageContractTest.java
This is safe to merge now as there is no published pact where the provider is adminusers and consumer is connector tagged with "master" and above (i.e. "test-fargate", "staging-fargate" etc). For reference the pact to be published is at https://github.com/alphagov/pay-connector/pull/4837.
=> PP-11279: Run the connector-adminusers messaging pact test

src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/main/java/uk/gov/pay/adminusers/persistence/entity/ServiceEntity.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceEntityFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java
- Sets `firstCheckedForArchivalDate` when a service is NOT archived.
- This date is used to archive service when no transactions/created_date exist.
- Also sets `skipCheckingForArchivalUntilDate`. This is used to skip checking services for archiving if there are active payments or recently created services.
- The date is calculated in this order 
1.  last transaction date + archiveServicesAfterDays 
2. created_date + archiveServicesAfterDays 
3. firstCheckedForArchivalDate + archiveServicesAfterDays
=> PP-11205 Set and use new columns when archiving services

src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceDao.java, src/test/java/uk/gov/pay/adminusers/fixtures/ServiceEntityFixture.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceDaoIT.java, src/test/java/uk/gov/pay/adminusers/utils/DatabaseTestHelper.java
- Update the DAO method to use new date fields to select services for archiving
=> PP-11811 Update DAO method to find services to archive

src/main/java/uk/gov/pay/adminusers/expungeandarchive/resource/ExpungeAndArchiveHistoricalDataResource.java, src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/resource/ExpungeAndArchiveHistoricalDataResourceIT.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java
- Merges service changes after dates used for archiving are set
- and added a resource test
=> PP-11811 Merge service changes

src/main/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataService.java, src/main/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDao.java, src/test/java/uk/gov/pay/adminusers/expungeandarchive/service/ExpungeAndArchiveHistoricalDataServiceTest.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/ServiceRoleDaoIT.java
- Log user IDs when users are removed from service after a service is archived. This will be useful when a service is accidentally archived and we have to reinstate users
=> PP-11812 Log when users are removed from service

.github/dependabot.yml
Tell Dependabot to ignore dropwizard-testing-junit4 version 4 because it only works with Dropwizard 4.x and we are using Dropwizard 3.x.
=> BAU — Tell Dependabot to ignore dropwizard-testing-junit4 version 4

m1/arm64.Dockerfile
The m1 dockerfile uses ubuntu as a base container instead of alpine. Run apt-get upgrade at build time
=> PP-11990: Run apt-get upgrade for m1 containers

.github/dependabot.yml
Include a version in the comment about dropwizard-testing-junit4 in the Dependabot configuration.
=> PP-12520 Dependabot: fix comment about dropwizard-testing-junit4

.github/workflows/_run-tests.yml
- Updated job name so in GitHub checks it appears as `PR / tests / App as provider tests / Contract tests (pull_request) ` instead of `PR / tests / App as provider contract tests / Contract tests (pull_request) `
=> PP-12570 Update GitHub action job name

pom.xml, src/main/java/uk/gov/pay/adminusers/app/AdminUsersApp.java
Updating to testcontainers through pay-java-commons has triggered an unwanted error leading InviteResourceServiceCompleteIT.shouldReturn400_whenUnsupportedSecondFactorMethodSupplied failing. `JsonProcessingExceptionMapper` defaults to not showing details of the validation/processing error.
- update pay-java-commons to `1.0.20240528083746`
- register `JsonProcessingExceptionMapper` with showDetails set to true
=> PP-12177 update exception mapper

.github/dependabot.yml, .github/workflows/_run-tests.yml, .github/workflows/codeql.yml, .secrets.baseline, Dockerfile, m1/arm64.Dockerfile, pom.xml, src/test/java/uk/gov/pay/adminusers/persistence/dao/GovUkPayAgreementDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/StripeAgreementDaoIT.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/UserDaoIT.java
- Upgrades to Java 21
- Also upgrades pact provider plugin
- Updated some tests for datetime granularity as they were failing on Github Actions due to Instant() returning time with nano-second granularity and values from the database are at the microsecond level. nano-second granularity shouldn't be an issue as Postgres supports only up to microsecond resolution (https://www.postgresql.org/docs/15/datatype-datetime.html) and in the API we are returning date/time in milliseconds (ex: https://github.com/alphagov/pay-adminusers/blob/master/openapi/adminusers_spec.yaml#L1228)
=> PP-12726 Upgrade to Java 21

pom.xml, src/main/java/uk/gov/pay/adminusers/persistence/entity/InviteEntity.java, src/test/java/uk/gov/pay/adminusers/persistence/dao/InviteDaoIT.java
- Fixes flakey test by truncating Instant to microseconds before inserting into DB. Truncating at the time of asserting field rounds up the microsecond precision which doesn't match the DB value and causes the test (`InviteDaoIT.create_shouldCreateAnInvite`) to fail
- Also removed unused library
=> PP-12726 Fix flakey test

src/main/java/uk/gov/pay/adminusers/utils/dispute/DisputeReasonMapper.java, src/test/java/uk/gov/pay/adminusers/utils/dispute/DisputeReasonMapperTest.java
Replace a switch statement with a switch expression (with pattern matching!) just because we can now we’re using Java 21.
Add some more tests (which pass with both the old code and the new code to ensure we’re not changing any behaviour).
(The old code used Apache Commons’ `StringUtils.isBlank(…)`, which uses `Character.isWhitespace(char)`, which does not support supplementary characters. The new code uses `String.isBlank(…)`, which uses `Character.isWhitespace(int)`, which does support supplementary characters. It is my understanding that all whitespace characters belong to the basic multilingual plane, so this should not change any behaviour. If I am wrong, the behaviour change is likely to be inconsequential: some `"other"` outputs may become `"unknown"` — but it seems extremely …
=> BAU — Replace switch statement with switch expression with patterns

.secrets.baseline, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/resources/UserResource.java
The latest IT Healthcheck identified a number of logging statements which could potentially result in unsanitised PII being logged. In several of these cases, these logging statements were found to be unnecessary as the relevant information is already logged in the API call, so they are being removed rather than spending time investigating the risk around logging PII.
- remove unnecessary logging statements
=> PP-12767 remove unnecessary logging

.github/dependabot.yml, pom.xml, src/main/java/uk/gov/pay/adminusers/persistence/dao/RoleDao.java
Upgrade project to use Guice v6
Add Transactional annotation to RoleDao. It was missing and Guice 6 is a stricter implementation.
=> PP-11723 upgrade guice to v6

pom.xml, src/test/java/uk/gov/pay/adminusers/client/ledger/service/LedgerServiceConsumerTest.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeEvidenceSubmittedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeLostEventQueueConsumerIT.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeWonEventQueueConsumerIT.java, src/test/resources/pacts/adminusers-ledger-get-payment-transaction.json
`pay-java-commons` was upgraded to Java 21. Some of the imports needed update as they are transative dependencies.
also fix pact test (unnecessary , in json file)
=> PP-12789 upgrade to pay-java-commons

.secrets.baseline, openapi/adminusers_spec.yaml, src/main/java/uk/gov/pay/adminusers/model/CreateServiceRequest.java, src/main/java/uk/gov/pay/adminusers/model/ServiceNamesDeserializer.java, src/main/java/uk/gov/pay/adminusers/resources/ServiceResource.java, src/main/java/uk/gov/pay/adminusers/service/LinksBuilder.java, src/test/java/uk/gov/pay/adminusers/resources/IntegrationTest.java, src/test/java/uk/gov/pay/adminusers/resources/ServiceResourceCreateIT.java, src/test/java/uk/gov/pay/adminusers/unit/service/ServiceResourceCreateTest.java
Following the general pattern in most of our Dropwizard codebases, we want to avoid JsonNode as the POST request body where possible so we can advantage of using javax Validation constraints.
It is also generally agreed that using hard coded URL strings makes for easier-to-read code.
Added a few more test cases in ServiceResourceCreateIT to reflect the pact tests between selfservice and adminusers:
* [a valid create service request with empty object](https://github.com/alphagov/pay-selfservice/blob/b2053a1049bc28813e8e7363245ad546ef19b675/test/pact/adminusers-client/service/create-service.pact.test.js#L50)
* [a valid create service request with gateway account ids](https://github.com/alphagov/pay-selfservice/blob/b2053a1049bc28813e8e7363245ad546ef19b675/test/pact/adminusers-client/service/ …
=> PP-13030: Use CreateServiceRequest pojo instead of JsonNode

src/main/resources/migrations/00089_create_procedure_check_and_execute.sql
Add stored procedure check_and_execute which allows specifying SQL, the table, and expected number of rows affected. This should allow ad-hoc modifications to be done more safely since it will automatically error if the number of rows affected wasn't exactly what you had intended
This is based on the prior art in https://github.com/alphagov/pay-connector/pull/5451/ and the RFC https://github.com/alphagov/pay-architecture/discussions/147
The formatting of the liquibase migrations meant I had to slightly edit the sql and replace the $$ quoted multi line string with single `'` quotes (and change all single quotes inside it to 2 x single quotes `''` (not double quotes)
- Locally run up pay local with this branch of adminusers `pay local up --cluster card --local adminusers`
- Once it's …
=> PP-13026: Add stored procedure to allow safer manual sql execution

pom.xml, src/main/java/uk/gov/pay/adminusers/app/config/AdminUsersModule.java, src/test/java/uk/gov/pay/adminusers/fixtures/EventFixtureUtil.java, src/test/java/uk/gov/pay/adminusers/infra/AppWithPostgresAndSqsRule.java, src/test/java/uk/gov/pay/adminusers/infra/AppWithPostgresExtension.java, src/test/java/uk/gov/pay/adminusers/infra/SqsTestDocker.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeCreatedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeEvidenceSubmittedEventQueueConsumerIT.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeLostEventQueueConsumerIT.java, src/test/java/uk/gov/pay/adminusers/pact/queuemessage/DisputeWonEventQueueConsumerIT.java, src/test/java/uk/gov/pay/adminusers/queue/event/EventSubscriberQueueTest.java, src/test/resources/config/test-it-config.yaml
The AWS SDK for Java 1.x is in maintenance mode, effective July 31, 2024. The AWS SDK for Java 1.x will no longer receive updates for new or existing services. We need to upgrade `pay-adminuers` to use the AWS SDK version 2 for SQS operations. This will involve updating dependencies, refactoring code to accommodate changes in the SDK, and ensuring the new SDK's methods and patterns are followed.
=> PP-13647 update AWS SDK to version 2
